-- OnpointDoc - Synchronisation des tickets depuis Google Sheet
-- Date: 2025-12-09
-- Généré automatiquement depuis scripts/sync-tickets-from-google-sheet.mjs
-- Total: 1462 tickets
-- Note: Ces tickets sont pour des entreprises spécifiques (affects_all_companies = false)

-- ============================================
-- ÉTAPE 1: Créer la table temporaire
-- ============================================

CREATE TEMP TABLE IF NOT EXISTS temp_tickets_csv (
  jira_issue_key TEXT NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  ticket_type ticket_type_t,
  priority priority_t,
  canal canal_t,
  status TEXT NOT NULL,
  module_name TEXT,
  submodule_name TEXT,
  feature_name TEXT,
  bug_type bug_type_enum,
  reporter_name TEXT,
  contact_user_name TEXT,
  company_name TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ
);

-- ============================================
-- ÉTAPE 2: Insérer les données dans la table temporaire
-- ============================================


INSERT INTO temp_tickets_csv (
  jira_issue_key,
  title,
  description,
  ticket_type,
  priority,
  canal,
  status,
  module_name,
  submodule_name,
  feature_name,
  bug_type,
  reporter_name,
  contact_user_name,
  company_name,
  created_at,
  updated_at,
  resolved_at
) VALUES
  ('OD-1405', 'A l''importation des journaux un message s''affiche d''erreur disant que le code journal n''existe pas', 'A l''importation des journaux un message s''affiche d''erreur disant que le code journal n''existe pas. Quelque soit le code journal qu’on sélectionne', 'BUG'::ticket_type_t, 'Low'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'JOEL SIE', 'M. KOFFI', 'EDIPRESSE', '2024-03-06 09:56:00+00'::timestamptz, NULL, '2024-03-08 08:28:00+00'::timestamptz),,
  ('OD-1340', 'Non affichage du grand livre tiers', 'Le grand livre tiers ne s’affiche pas pour EDIPRESSE. Il tourne en boucle', 'BUG'::ticket_type_t, 'Low'::priority_t, 'E-mail'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'JOEL SIE', 'M. KOFFI', 'EDIPRESSE', '2024-02-19 15:19:00+00'::timestamptz, NULL, '2024-02-21 14:53:00+00'::timestamptz),,
  ('OD-1190', 'Il y a un message d''erreur lorsqu''on enregistre une programmation de salaire', 'Il y a un message d’erreur lorsqu’on enregistre une programmation de salaire pour un mois donné,
  ('OD-1187', 'Erreur sur Contrat à durée Indéterminé / Déterminé avec Essai', 'Lorsque le type de Contrat avec mention “Avec Essai“ est sélectionné dans un contrat', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Priorité 4', 'Appel Téléphonique', 'RH', '2024-01-04 15:33', 'Autres'::bug_type_enum, 'une erreur Ajax apparait au calcul de la paie.', 'Edwige KOUASSI', 'Edwige MESSOU', NULL, '2023-12-29 12:32:00+00'::timestamptz, NULL),,
  ('OD-1204', 'Erreur serveur', 'Erreur serveur', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Global', 'Global', 'Global', 'Page d''erreur'::bug_type_enum, 'JOEL SIE', 'M. Coulibaly', 'KORI TRANSPORT', '2024-01-04 15:03:00+00'::timestamptz, NULL, '2024-01-08 14:20:00+00'::timestamptz),,
  ('OD-1307', 'Impossible d''exporter les expressions de besoins', 'A l’export des expressions de besoins la page tourne et rien ne s’affiche', 'BUG'::ticket_type_t, 'Low'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Opérations', 'Achat', NULL, 'Enregistrement impossible'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'SEY ARTHUR', 'ENVAL LABORATOIRE', '2024-02-06 13:05:00+00'::timestamptz, NULL, '2024-02-07 09:22:00+00'::timestamptz),,
  ('OD-1376', 'Serveur erreur ''''SERVICE UNAVAIBLE''''', 'Serveur erreur', 'BUG'::ticket_type_t, 'Low'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Global', 'Global', 'Global', 'Page d''erreur'::bug_type_enum, 'JOEL SIE', NULL, 'ONPOINT', '2024-02-29 10:29:00+00'::timestamptz, NULL, '2024-03-04 06:02:00+00'::timestamptz),,
  ('OD-1370', 'Doublon constaté lors de la programmation de paiement fournisseur', 'Après enregistrement d’une première programmation fournisseur', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Priorité 4', 'En présentiel', 'Opérations', '2024-03-28 10:51', 'Autres'::bug_type_enum, 'quand on retourne dans le formulaire la programmation déjà enregistrée apparait dans la liste de factures à programmer.', 'N''GBRA MOYE BERNICE DORIS', 'Gaelle TOURE', NULL, '2024-02-27 18:42:00+00'::timestamptz, NULL),,
  ('OD-1341', 'Non affichage de données quand on sélectionne un projet dans le filtre du rapport détaillé des dettes factures fournisseurs', 'Le filtre “*projet*” dans le *rapport détaillé des dettes factures fournisseurs* ne déverse aucune donnée pourtant des factures ont été saisies en choisissant ile projet sélectionné.', 'BUG'::ticket_type_t, 'Low'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Opérations', 'Achat', NULL, 'Dysfonctionnement des filtres'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'STEPHANE MOGOU', 'MATRELEC', '2024-02-19 15:32:00+00'::timestamptz, NULL, '2024-02-21 14:53:00+00'::timestamptz),,
  ('OD-516', 'Ordre de Mission avec même référence', 'Ordre de mission ayant les mêmes références quand c''est fait pour un agent le même jour', 'BUG'::ticket_type_t, 'Low'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'RH', 'Documents', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:45:00+00'::timestamptz, NULL, '2024-03-12 17:11:00+00'::timestamptz),,
  ('OD-506', 'Soucis sur Fonctionnalités : Impossible d''enregistrer un BL avec des fichiers en pièce joints', 'Impossible d''enregistrer un BL avec des fichiers en pièce joints', 'BUG'::ticket_type_t, 'High'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Opérations', 'Achat', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:44:00+00'::timestamptz, '2023-12-19 20:03:00+00'::timestamptz, '2023-12-19 20:03:00+00'::timestamptz),,
  ('OD-867', 'Visibilité de l''organigramme', 'Une partie de l''organigramme ne s''affiche pas . Il faut réduire la taille de l''écran avant de voir l''organigramme en entier', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'En présentiel'::canal_t, 'Terminé(e)', 'RH', 'Paramétrage', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'ENVAL LABORATOIRE', '2023-12-04 13:57:00+00'::timestamptz, NULL, '2024-08-22 11:56:00+00'::timestamptz),,
  ('OD-865', 'Accès au bouton calculer dans calcul OHADA', 'Dans le formulaire calcul OHADA il y a un employé qui n''a pas accès au bouton calculer malgré la revue des accès effectuée à mon niveau', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'RH', 'Salaire', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'ENVAL LABORATOIRE', '2023-12-04 13:57:00+00'::timestamptz, NULL, '2024-03-28 16:39:00+00'::timestamptz),,
  ('OD-863', 'Lorsqu''on met des filtres en historique de encaissement client', 'le montant total ne prend pas en compte le filtre', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'OBC Customer Support', NULL, 'Constat Interne', '6/12/2023 17:32', 'Autres'::bug_type_enum, 'Lorsqu''on met des filtres en historique de encaissement client', 'le montant total ne prend pas en compte le filtre', 'Vivien DAKPOGAN', NULL, NULL, '2023-12-04 13:56:00+00'::timestamptz),,
  ('OD-830', 'On constate que les comptes tiers se désélectionnent après l''enregistrement d''écritures manuelle', 'On constate que les comptes tiers se désélectionnent après l''enregistrement d''écritures manuelle', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:55:00+00'::timestamptz, NULL, '2024-03-12 17:12:00+00'::timestamptz),,
  ('OD-825', 'Modification Ecritures manuelle', 'A la modification des écritures manuel la liste des tiers ne se déversent pas automatiquement. Quand on réussit a sélectionner le compte tiers (Après avoir décocher et décocher certains champ) il n''apparait pas en historique.', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'JOEL K PROPERTIES', '2023-12-04 13:54:00+00'::timestamptz, NULL, '2024-05-10 18:17:00+00'::timestamptz),,
  ('OD-824', 'L''archivage des numéros d''imputation est incorrect lorsqu''on modifie l''écriture en changeant de journal comptable', 'L''archivage des numéros d''imputation est incorrect lorsqu''on modifie l''écriture en changeant de journal comptable', 'BUG'::ticket_type_t, 'High'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Global', 'Global', 'Global', 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:54:00+00'::timestamptz, NULL, '2024-06-06 16:08:00+00'::timestamptz),,
  ('OD-823', 'L''impression d''un grand livre mensuel prend en compte le solde initial du compte', 'L''impression d''un grand livre mensuel prend en compte le solde initial du compte', 'BUG'::ticket_type_t, 'High'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:54:00+00'::timestamptz, NULL, '2024-05-15 10:07:00+00'::timestamptz),,
  ('OD-809', 'Bug - Production', 'Suppression Bordereau de sortie Impossible (Génération message d''erreur)-- Erreur de suppression de l''enregistrement. Message: Une erreur s''est produite lors de la mise à jour des entrées. Pour plus d''informations', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'OBC Customer Support', NULL, 'Constat Interne', '17/5/2024 08:36', 'Autres'::bug_type_enum, 'consultez l''exception interne. StackTrace: at System.Data.Entity.Internal.InternalContext.SaveChanges() at ONPOINTBUSINESSCENTER.Controllers.BordeSortieController.DeleteConfirmed(Int32 id', 'String motif)', 'Vivien DAKPOGAN', NULL, NULL, '2023-12-04 13:53:00+00'::timestamptz),,
  ('OD-794', 'Impossible d''effectuer des suppressions', 'Doublon d''écritures impossible à supprimer', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:52:00+00'::timestamptz, NULL, '2023-12-06 17:33:00+00'::timestamptz),,
  ('OD-791', 'Message d''erreur à l''exportation de la base dette fournisseur', 'Message d''ereur à l''exportation de la base dette fournisseur', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Opérations', 'Achat', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'KORI TRANSPORT', '2023-12-04 13:51:00+00'::timestamptz, NULL, '2024-05-05 18:46:00+00'::timestamptz),,
  ('OD-2167', 'Afficher le nom complet des employés lors dans les listes déroulantes sélectionner un employé', 'Afficher le nom complet des employés lors dans les listes déroulantes sélectionner un employé,
  ('OD-2137', 'Le type de demande dans le suivi de commande de pièces est dysfonctionnel', 'Le type de demande dans le suivi de commande de pièces est dysfonctionnel,
  ('OD-2136', 'Les prix unitaires des articles de stock n''apparaissent pas dans le formulaire de la maintenance curative.', 'Les prix unitaires des articles de stock n''apparaissent pas dans le formulaire de la maintenance curative.', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Opérations', 'Gestion de stock', NULL, 'Mauvais déversement des données'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'Koné SEYDOU', 'VENUS DISTRIBUTION', '2024-10-30 10:57:00+00'::timestamptz, NULL, '2024-11-06 18:20:00+00'::timestamptz),,
  ('OD-2134', 'Le nom complet des employés dans le formulaire de demande de sortie n''apparait plus.', 'Le nom complet des employés dans le formulaire de demande de sortie n''apparait plus.', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Opérations', 'Gestion de stock', NULL, 'Mauvais déversement des données'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'Koné SEYDOU', 'VENUS DISTRIBUTION', '2024-10-30 10:14:00+00'::timestamptz, NULL, '2024-11-06 18:19:00+00'::timestamptz),,
  ('OD-2103', 'Nous constatons à l''enregistrement d''un bordereau de transfert seulement deux articles qui se déversent au lieu d''une vingtaine d''articles', 'Nous constatons à l''enregistrement d''un bordereau de transfert seulement deux articles qui se déversent au lieu d''une vingtaine d''articles,
  ('OD-2102', 'Impossible d''enregistrer un stock initial malgré que le magasin ne soit pas en historique des bordereaux d''entrée', 'Impossible d''enregistrer un stock initial malgré que le magasin ne soit pas en historique des bordereaux d''entrée,
  ('OD-2097', 'L''affichage de requêtes workflows indisponible pour la validation des factures ventes', 'L''affichage de requêtes workflows indisponible pour la validation des factures ventes et autres.,
  ('OD-2049', 'Enregistrement de la demande sortie impossible', 'Enregistrement de la demande sortie impossible', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Opérations', 'Gestion de stock', NULL, 'Enregistrement impossible'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'Koné SEYDOU', 'VENUS DISTRIBUTION', '2024-09-26 17:26:00+00'::timestamptz, NULL, '2024-09-27 16:18:00+00'::timestamptz),,
  ('OD-799', 'Erreur Serveur', 'Serveur error donc impossible d''accéder à OBC', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Global', 'Global', 'Global', 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'VENUS DISTRIBUTION', '2023-12-04 13:52:00+00'::timestamptz, NULL, '2023-12-06 12:33:00+00'::timestamptz),,
  ('OD-1706', 'La liste déroulante secteur d’activité vide dans les fonctionnalités gestion des prospects et gestion des clients .', '* La liste déroulante secteur d’activité vide dans les fonctionnalités gestion des prospects et gestion des clients .', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'E-mail'::canal_t, 'Terminé(e)', 'CRM', 'Client', NULL, 'Autres'::bug_type_enum, 'JOEL SIE', 'MYRIAM', 'ONPOINT', '2024-05-31 09:55:00+00'::timestamptz, NULL, '2024-06-07 15:25:00+00'::timestamptz),,
  ('OD-884', 'Montants non programmés affiché sur le dashboard accueil n''est pas exacte', 'Le montant non programmé dans le sous module impots et taxes est différent du montant impots et taxes non programmé qui s’affiche sur le dashboard', 'BUG'::ticket_type_t, 'High'::priority_t, 'En présentiel'::canal_t, 'Terminé(e)', 'Finance', 'Analytique', NULL, 'Autres'::bug_type_enum, 'JOEL SIE', 'KOFFI MARIUS', 'ONPOINT', '2023-12-06 16:43:00+00'::timestamptz, NULL, '2024-01-17 17:10:00+00'::timestamptz),,
  ('OD-2603', 'Lors de la paie', 'toute les références se déversent', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Bug', 'KOFFI & DIABATE', NULL, 'Terminé(e)', 'Autres'::bug_type_enum, '!image-20250516-145511.png|width=1860', 'height=1103', 'alt=image-20250516-145511.png!,
  ('OD-2602', 'RH : Lorsqu''on fais la paie', 'le calcul des nets est incorrectes', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Priorité 1', 'Appel Téléphonique', 'RH', '2025-05-21 11:52', 'Autres'::bug_type_enum, 'Le net devrait être égale au Salaire brut-les cotisations+les indemnités non imposables -les retenues non imposables', 'EVA BASSE', 'LYDIE N''GUESSAN', NULL, '2025-05-16 11:47:00+00'::timestamptz, NULL),,
  ('OD-2601', 'RH: Quand on calcul une paie', 'l''historique n''apparait ou réapparais après un long moment et disparais', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'OBC Customer Support', NULL, 'Appel Téléphonique', '21/5/2025 12:03', 'Autres'::bug_type_enum, 'RH: Quand on calcul une paie', 'l''historique n''apparait ou réapparais après un long moment et disparais', 'EVA BASSE', NULL, NULL, '2025-05-16 11:44:00+00'::timestamptz),,
  ('OD-2552', 'Document RH: Lenteur d''affichage au lancement du livre de paie', 'Document RH: Lenteur d''affichage au lancement du livre de paie', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'RH', 'Documents', NULL, 'Lenteur Système'::bug_type_enum, 'EVA BASSE', 'LYDIE N''GUESSAN', 'KOFFI & DIABATE', '2025-04-24 15:18:00+00'::timestamptz, NULL, '2025-04-29 08:28:00+00'::timestamptz),,
  ('OD-2431', 'Impossible d''imprimer des bulletins sur deux années simultanément (exemple : Novembre 2024 à Février 2025)', 'Impossible d''imprimer des bulletins sur deux années simultanément (exemple : Novembre 2024 à Février 2025)', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'E-mail'::canal_t, 'Terminé(e)', 'RH', 'Documents', NULL, 'Mauvais déversement des données'::bug_type_enum, 'EVA BASSE', 'LYDIE N''GUESSAN', 'KOFFI & DIABATE', '2025-03-19 10:53:00+00'::timestamptz, NULL, '2025-04-01 11:10:00+00'::timestamptz),,
  ('OD-2339', 'Dysfonctionnement du calcul d''ancienneté (plus de 25 ans)', 'Lors du calcul de la paie', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Bug', 'KOFFI & DIABATE', NULL, 'Terminé(e)', 'Autres'::bug_type_enum, 'pour un salarié ayant plus de 28 ans d’ancienneté', 'le taux d’ancienneté est à 24 % or le mois d’avant', 'nous étions à 25%', NULL, NULL, NULL),,
  ('OD-2277', 'Mauvais calcul de l''ancienneté', 'Un employé a été embauché le 01/01/1996 et en Décembre 2024', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'OBC Customer Support', 'Online (Google Meet', 'Teams...)', '12/12/2024 15:15', 'Autres'::bug_type_enum, 'OBC lui donne 24% au lieu de 25% et l’ancienneté est à 25 ans au lieu de 28 ans.', 'EVA BASSE', 'LYDIE N''GUESSAN', NULL, NULL, '2024-12-11 10:25:00+00'::timestamptz),,
  ('OD-2272', 'Impossible de calculer la paie de Décembre (Voir capture joint)', 'Impossible de calculer la paie de Décembre (Voir capture joint)', NULL, 'Critical'::priority_t, 'Online (Google Meet, Teams...)'::canal_t, 'Priorité 1', 'Teams...)', 'RH', '2024-12-10 20:05', 'Autres'::bug_type_enum, 'EVA BASSE', 'LYDIE N''GUESSAN', 'KOFFI & DIABATE', NULL, '2024-12-10 12:03:00+00'::timestamptz, '2024-12-10 20:05:00+00'::timestamptz),,
  ('OD-2157', 'Message d''erreur', 'Message d''erreur,
  ('OD-2654', 'Finance/Comptabilité Générale/ Journal Général - La Suppression d''une opération dans Journal général est impossible et Plante l’application', 'Suppression opération Journal général impossible - Plante l’application,
  ('OD-2551', 'RAN : Lorsqu''on génère le RAN avec l''option nature de comptes Comptes généraux uniquement', 'le Ran est correcte mais lorsqu''on choisi Comptes généraux et tiers', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Bug', 'Raïssa CAMARA', 'JOEL K PROPERTIES', 'Terminé(e)', 'Autres'::bug_type_enum, 'le RAN est incorecte', 'RAN : Lorsqu''on génère le RAN avec l''option nature de comptes Comptes généraux uniquement', 'le Ran est correcte mais lorsqu''on choisi Comptes généraux et tiers', NULL, NULL, NULL),,
  ('OD-2256', 'Finance / Imputation - Malgré les paramétrages de la natures de prestation', 'aucune écritures ne se déversent dans la compta', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Bug', 'Joel A', 'JOEL K PROPERTIES', 'Terminé(e)', 'Autres'::bug_type_enum, 'Finance / Imputation - Malgré les paramétrages de la natures de prestation', 'aucune écritures ne se déversent dans la compta,
  ('OD-844', 'Erreur sur fonction Enregistrer Facture Achat', 'Erreur fonction Enregistrer facture achat Détails : Controleur : FactureFournisseur | Action : Index Message : Nullable object must have a value. tackTrace : at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) at ONPOINTBUSINESSCENTER.Controllers.FactureFournisseurController.<>c.<Index>b__5_16(achat_facture_fournisseur c) at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() at System.Linq.Enumerable.Sum(IEnumerable`1 source) at ONPOINTBUSINESSCENTER.Controllers.FactureFournisseurController.Index(String filter', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Object[] ) at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext', 'String filterDateFin', 'Int32 page', 'JOEL K PROPERTIES', 'Autres'::bug_type_enum, 'String filterFournisseur', 'String filterTypeAxe', 'String filterValeurAxe', NULL, NULL, NULL),,
  ('OD-819', 'Ancienneté de moins d''un an non pris en compte sur les bulletins', 'L''ancienneté ne figure pas sur les bulletins quand il s''agit d''un employé ayant un contrat de moins d''une année', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'RH', 'Documents', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'JOEL K PROPERTIES', '2023-12-04 13:54:00+00'::timestamptz, NULL, '2023-12-06 17:32:00+00'::timestamptz),,
  ('OD-817', 'DUPLICATA CONTRAT', 'Au clique sur le bouton pour un enregistrement le formulaire n''affiche pas.', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'RH', 'Gestion employé', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'JOEL K PROPERTIES', '2023-12-04 13:54:00+00'::timestamptz, NULL, '2023-12-06 17:32:00+00'::timestamptz),,
  ('OD-1267', 'Le montant de la rubrique assurance maladie santé n''est pas récupéré dans le calcul de salaire de janvier 2024,Le montant de la rubrique “assurance maladie santé” n''est pas récupéré dans le calcul de salaire de janvier 2024,N''GBRA MOYE BERNICE DORIS,AKA,EGBV,,Appel Téléphonique,RH,Salaire,Bug,Récupération de données impossible,OBC Customer Support,Priorité 4,Terminé(e),2024-01-19 20:33,25/1/2024 08:07,2024-01-25 08:07,', NULL, NULL, 'Critical'::priority_t, 'autre'::canal_t, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),,
  ('OD-2182', 'Nous constatons dans le grand livre général que le compte 139000 (écriture du résultat net RAN) est lié au code journal PCAISS (petite caisse)', 'Nous constatons dans le grand livre général que le compte 139000 (écriture du résultat net RAN) est lié au code journal PCAISS (petite caisse).,
  ('OD-2113', 'Mauvais affichage de livre de paie général', 'Nous constatons un mauvais affichage du livre de paie général avec les employés qui ne s’affichent plus par ordre alphabétique ainsi que le nombre total de salariés .', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'RH', 'Documents', NULL, 'Page d''erreur'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'AKA', 'EGBV', '2024-10-23 15:55:00+00'::timestamptz, '2024-10-28 10:46:00+00'::timestamptz, '2024-10-28 10:46:00+00'::timestamptz),,
  ('OD-793', 'Le formulaire des opérations de caisse s''affiche lorqu''on qu''on clic sur nouvelle opération dans l''onglet historique', 'Afficher le formulaire lorsqu''on clic sur formulaire', 'BUG'::ticket_type_t, 'High'::priority_t, 'Constat Interne'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'Vivien DAKPOGAN', NULL, 'AFRIC URBA', '2023-12-04 13:52:00+00'::timestamptz, NULL, '2023-12-06 17:33:00+00'::timestamptz),,
  ('OD-874', 'Impossible de supprimer un bordereau de sortie - Enregistrer et non valider', 'Suppression de bordereau de sortie Impossible. Génération de message d''erreur au clique du bouton Supprimer. Détails erreur : Début { Erreur de suppression de l''enregistrement. Message: Une erreur s''est produite lors de la mise à jour des entrées. Pour plus d''informations', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'OBC Customer Support', NULL, 'Constat Interne', '15/4/2024 18:45', 'Autres'::bug_type_enum, 'consultez l''exception interne. StackTrace: at System.Data.Entity.Internal.InternalContext.SaveChanges() at ONPOINTBUSINESSCENTER.Controllers.BordeSortieController.DeleteConfirmed(Int32 id', 'String motif) } Fin', 'Vivien DAKPOGAN', NULL, NULL, '2023-12-04 13:58:00+00'::timestamptz),,
  ('OD-834', 'Lors de l''édition', 'le champ Effet apparait 3 Fois', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'Bug', 'M. ECARE', 'KORI TRANSPORT', 'Terminé(e)', 'Autres'::bug_type_enum, 'et impossible d''enregistrer le formulaire tant que les 3 champs ne sont pas saisis.', 'Lors de l''édition', 'le champ Effet apparait 3 Fois', NULL, NULL, NULL),,
  ('OD-795', 'Taxes PPSI', 'Pour des factures avec la taxe PPSI', NULL, 'Critical'::priority_t, 'autre'::canal_t, 'OBC Customer Support', NULL, 'Constat Interne', '6/12/2023 17:33', 'Autres'::bug_type_enum, 'c''est le montant net qui devrait se déverser à la programmation afin d''être exécuter par la suite Mais actuellement', 'OBC récupère le montant TTC', 'Vivien DAKPOGAN', NULL, NULL, '2023-12-04 13:52:00+00'::timestamptz),,
  ('OD-1853', 'Mauvaise récupération de données de gratification pour la formule salaire brut', 'Mauvaise récupération de données de gratification pour la formule salaire brut,
  ('OD-2835', 'RH/Gestion Employé/Contrat - Impossible d''importer un fichier import', 'Impossible d''importer un fichier import', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'Constat Interne'::canal_t, 'En cours', 'RH', 'Gestion employé', NULL, 'Enregistrement impossible'::bug_type_enum, 'Edwige KOUASSI', NULL, 'ENVIPUR', '2025-09-03 01:35:00+00'::timestamptz, NULL, NULL),,
  ('OD-1808', 'Des postes comptable en doublons ayant générées les mêmes écritures (Les doublons à supprimer)', 'Des postes comptable en doublons ayant générées les mêmes écritures (Les doublons à supprimer)', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'Terminé(e)', 'Finance', 'Comptabilité Générale', NULL, 'Autres'::bug_type_enum, 'JOEL SIE', 'HAMED DOUMBIA', 'ROCFED', '2024-07-10 10:11:00+00'::timestamptz, NULL, '2024-07-11 17:02:00+00'::timestamptz),,
  ('OD-2789', 'PROJET/TIMESHEET/Problème constaté sur l''enregistrement des timesheet journaliers', 'PROJET/TIMESHEET/Problème constaté sur l''enregistrement des timesheet journaliers quand on clique sur le bouton enregistrer ,
  ('OD-2942', 'RH/Salaire / Opération de paie ODP - Différence de montant entre la valeur trouvé dans le détails et celle affiché en Historique', 'Nous constatons une différence entre la valeur dans le détails et celle affiché en Historique,
  ('OD-2745', 'RH/DOCUCMENTS/BULLETIN DE SALAIRE : Nous constatons un mauvais déversement des congés dus sur le bulletin de salaire', 'RH/DOCUCMENTS/BULLETIN DE SALAIRE : Nous constatons un mauvais déversement des congés dus sur le bulletin de salaire.,
  ('OD-2733', 'RH/Fichier du personnel/ Import fichier  - Impossible d''importer le fichier du personnel', 'Impossible d’importer des données à partir du formulaire CSV - Fichier du personnel', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'autre'::canal_t, 'En cours', 'RH', 'Gestion employé', NULL, 'Enregistrement impossible'::bug_type_enum, 'Edwige KOUASSI', 'Gaelle TOURE', 'ONPOINT', '2025-07-28 18:35:00+00'::timestamptz, NULL, NULL),,
  ('OD-2723', 'Impossible de visualiser le dashboard activité commerciale', 'Impossible de visualiser le dashboard activité commerciale', 'BUG'::ticket_type_t, 'Critical'::priority_t, 'E-mail'::canal_t, 'Terminé(e)', 'CRM', 'Analytique', NULL, 'Page d''erreur'::bug_type_enum, 'N''GBRA MOYE BERNICE DORIS', 'FABIEN VATI', 'ONPOINT', '2025-07-28 10:41:00+00'::timestamptz, NULL, '2025-08-27 09:16:00+00'::timestamptz);;