-- OnpointDoc - Mise à jour des tickets d'assistance depuis l'export JIRA (PARTIE 6)
-- Date: 2025-12-10
-- Description: Met à jour created_at, duration_minutes, action_menee et objet_principal
-- Partie 6 sur 15 (500 tickets)

UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8113';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8112';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8111';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8110';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8109';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8108';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8106';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8105';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8104';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8101';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8100';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8099';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8098';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8097';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8096';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8095';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8094';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8092';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8091';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8090';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8089';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8088';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8087';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8086';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8085';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8084';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8083';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8082';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8065';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8064';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8063';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8062';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8060';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8059';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8058';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8057';
UPDATE tickets SET duration_minutes = 37, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8056';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8055';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8038';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8037';
UPDATE tickets SET duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8036';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8034';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8033';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8032';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8031';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8030';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8029';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8027';
UPDATE tickets SET duration_minutes = 13, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8025';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8024';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8023';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8022';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8020';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8019';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8016';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8014';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8013';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8012';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8011';
UPDATE tickets SET duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8010';
UPDATE tickets SET duration_minutes = 27, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8009';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8008';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8007';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8006';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8005';
UPDATE tickets SET duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8004';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8003';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7996';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7992';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7991';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7990';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7989';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7988';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7987';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7986';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7985';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7984';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7983';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7982';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7981';
UPDATE tickets SET duration_minutes = 16, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7980';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-7979';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7978';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Présentation' WHERE jira_issue_key = 'OBCS-7977';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7976';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7975';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7974';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7973';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7971';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7967';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7966';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7965';
UPDATE tickets SET created_at = '2024-11-29T19:18:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7943';
UPDATE tickets SET created_at = '2024-11-29T19:15:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7942';
UPDATE tickets SET created_at = '2024-11-29T19:11:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7941';
UPDATE tickets SET created_at = '2024-11-29T19:08:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7939';
UPDATE tickets SET created_at = '2024-11-29T19:04:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7938';
UPDATE tickets SET created_at = '2024-11-29T19:02:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7937';
UPDATE tickets SET created_at = '2024-11-29T19:01:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7936';
UPDATE tickets SET created_at = '2024-11-29T18:58:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7935';
UPDATE tickets SET created_at = '2024-11-29T18:55:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7934';
UPDATE tickets SET created_at = '2024-11-29T18:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7933';
UPDATE tickets SET created_at = '2024-11-29T18:51:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7932';
UPDATE tickets SET created_at = '2024-11-29T18:49:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7931';
UPDATE tickets SET created_at = '2024-11-29T18:47:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7930';
UPDATE tickets SET created_at = '2024-11-29T18:45:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7928';
UPDATE tickets SET created_at = '2024-11-29T18:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7919';
UPDATE tickets SET created_at = '2024-11-29T18:23:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7918';
UPDATE tickets SET created_at = '2024-11-29T18:19:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7917';
UPDATE tickets SET created_at = '2024-11-29T17:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7916';
UPDATE tickets SET created_at = '2024-11-29T17:54:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7915';
UPDATE tickets SET created_at = '2024-11-29T17:50:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7914';
UPDATE tickets SET created_at = '2024-11-29T17:50:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7913';
UPDATE tickets SET created_at = '2024-11-29T17:49:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7912';
UPDATE tickets SET created_at = '2024-11-29T17:47:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7911';
UPDATE tickets SET created_at = '2024-11-29T17:46:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7910';
UPDATE tickets SET created_at = '2024-11-29T17:42:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7909';
UPDATE tickets SET created_at = '2024-11-29T17:41:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7908';
UPDATE tickets SET created_at = '2024-11-29T17:38:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7907';
UPDATE tickets SET created_at = '2024-11-29T17:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7906';
UPDATE tickets SET created_at = '2024-11-29T17:36:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7905';
UPDATE tickets SET created_at = '2024-11-29T17:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7904';
UPDATE tickets SET created_at = '2024-11-29T17:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7903';
UPDATE tickets SET created_at = '2024-11-29T17:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7902';
UPDATE tickets SET created_at = '2024-11-29T16:48:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7900';
UPDATE tickets SET created_at = '2024-11-29T16:47:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7899';
UPDATE tickets SET created_at = '2024-11-29T16:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7898';
UPDATE tickets SET created_at = '2024-11-29T16:43:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7897';
UPDATE tickets SET created_at = '2024-11-29T16:42:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7896';
UPDATE tickets SET created_at = '2024-11-29T16:40:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7895';
UPDATE tickets SET created_at = '2024-11-29T16:37:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7894';
UPDATE tickets SET created_at = '2024-11-29T16:34:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7893';
UPDATE tickets SET created_at = '2024-11-29T16:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7892';
UPDATE tickets SET created_at = '2024-11-29T16:30:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7891';
UPDATE tickets SET created_at = '2024-11-29T16:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7890';
UPDATE tickets SET created_at = '2024-11-29T15:39:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7888';
UPDATE tickets SET created_at = '2024-11-29T15:39:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7887';
UPDATE tickets SET created_at = '2024-11-29T15:38:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7886';
UPDATE tickets SET created_at = '2024-11-29T15:37:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7885';
UPDATE tickets SET created_at = '2024-11-29T15:36:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7884';
UPDATE tickets SET created_at = '2024-11-29T15:36:00.000Z'::timestamptz, duration_minutes = 20, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7883';
UPDATE tickets SET created_at = '2024-11-29T15:34:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7882';
UPDATE tickets SET created_at = '2024-11-29T15:34:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7881';
UPDATE tickets SET created_at = '2024-11-29T15:31:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7880';
UPDATE tickets SET created_at = '2024-11-29T15:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7879';
UPDATE tickets SET created_at = '2024-11-25T13:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Kick-off de démarrage', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7852';
UPDATE tickets SET created_at = '2024-11-25T13:22:00.000Z'::timestamptz, duration_minutes = 5 WHERE jira_issue_key = 'OBCS-7851';
UPDATE tickets SET created_at = '2024-11-22T20:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7848';
UPDATE tickets SET created_at = '2024-11-22T20:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7847';
UPDATE tickets SET created_at = '2024-11-22T20:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7846';
UPDATE tickets SET created_at = '2024-11-22T20:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7845';
UPDATE tickets SET created_at = '2024-11-22T20:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7844';
UPDATE tickets SET created_at = '2024-11-22T20:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7843';
UPDATE tickets SET created_at = '2024-11-22T20:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7842';
UPDATE tickets SET created_at = '2024-11-22T20:01:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7841';
UPDATE tickets SET created_at = '2024-11-22T19:59:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7840';
UPDATE tickets SET created_at = '2024-11-22T19:57:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7839';
UPDATE tickets SET created_at = '2024-11-22T19:48:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7838';
UPDATE tickets SET created_at = '2024-11-22T19:46:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7837';
UPDATE tickets SET created_at = '2024-11-22T19:42:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7836';
UPDATE tickets SET created_at = '2024-11-22T19:38:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7835';
UPDATE tickets SET created_at = '2024-11-22T19:35:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7834';
UPDATE tickets SET created_at = '2024-11-22T19:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7833';
UPDATE tickets SET created_at = '2024-11-22T19:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7832';
UPDATE tickets SET created_at = '2024-11-22T18:29:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7814';
UPDATE tickets SET created_at = '2024-11-22T18:25:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7813';
UPDATE tickets SET created_at = '2024-11-22T18:24:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7812';
UPDATE tickets SET created_at = '2024-11-22T18:22:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7811';
UPDATE tickets SET created_at = '2024-11-22T18:20:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7810';
UPDATE tickets SET created_at = '2024-11-22T18:20:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7809';
UPDATE tickets SET created_at = '2024-11-22T17:48:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7808';
UPDATE tickets SET created_at = '2024-11-22T17:47:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7807';
UPDATE tickets SET created_at = '2024-11-22T17:47:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7805';
UPDATE tickets SET created_at = '2024-11-22T17:35:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7802';
UPDATE tickets SET created_at = '2024-11-22T17:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7801';
UPDATE tickets SET created_at = '2024-11-22T17:34:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7800';
UPDATE tickets SET created_at = '2024-11-22T17:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7799';
UPDATE tickets SET created_at = '2024-11-22T17:29:00.000Z'::timestamptz, duration_minutes = 18, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7798';
UPDATE tickets SET created_at = '2024-11-22T17:28:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7797';
UPDATE tickets SET created_at = '2024-11-22T17:22:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7796';
UPDATE tickets SET created_at = '2024-11-22T17:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7795';
UPDATE tickets SET created_at = '2024-11-22T17:18:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7794';
UPDATE tickets SET created_at = '2024-11-22T17:11:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7793';
UPDATE tickets SET created_at = '2024-11-22T17:11:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7792';
UPDATE tickets SET created_at = '2024-11-22T17:09:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7791';
UPDATE tickets SET created_at = '2024-11-22T17:08:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7790';
UPDATE tickets SET created_at = '2024-11-22T17:07:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7789';
UPDATE tickets SET created_at = '2024-11-22T17:07:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7788';
UPDATE tickets SET created_at = '2024-11-22T17:07:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7787';
UPDATE tickets SET created_at = '2024-11-22T17:07:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7786';
UPDATE tickets SET created_at = '2024-11-22T17:06:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7785';
UPDATE tickets SET created_at = '2024-11-22T17:06:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7784';
UPDATE tickets SET created_at = '2024-11-22T17:05:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7783';
UPDATE tickets SET created_at = '2024-11-22T17:05:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7782';
UPDATE tickets SET created_at = '2024-11-22T17:05:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7781';
UPDATE tickets SET created_at = '2024-11-22T17:05:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7780';
UPDATE tickets SET created_at = '2024-11-22T17:04:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7779';
UPDATE tickets SET created_at = '2024-11-22T17:04:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7778';
UPDATE tickets SET created_at = '2024-11-22T17:04:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7777';
UPDATE tickets SET created_at = '2024-11-22T17:03:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7776';
UPDATE tickets SET created_at = '2024-11-22T17:03:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7775';
UPDATE tickets SET created_at = '2024-11-22T17:02:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7774';
UPDATE tickets SET created_at = '2024-11-22T17:01:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7773';
UPDATE tickets SET created_at = '2024-11-22T17:00:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7772';
UPDATE tickets SET created_at = '2024-11-22T17:00:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7771';
UPDATE tickets SET created_at = '2024-11-22T16:57:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7770';
UPDATE tickets SET created_at = '2024-11-22T16:57:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7769';
UPDATE tickets SET created_at = '2024-11-22T16:56:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7768';
UPDATE tickets SET created_at = '2024-11-22T16:56:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7767';
UPDATE tickets SET created_at = '2024-11-22T16:56:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7766';
UPDATE tickets SET created_at = '2024-11-22T16:29:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7765';
UPDATE tickets SET created_at = '2024-11-22T15:56:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7763';
UPDATE tickets SET created_at = '2024-11-22T11:27:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7754';
UPDATE tickets SET created_at = '2024-11-22T11:23:00.000Z'::timestamptz, duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7753';
UPDATE tickets SET created_at = '2024-11-20T11:19:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7730';
UPDATE tickets SET created_at = '2024-11-20T11:18:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7729';
UPDATE tickets SET created_at = '2024-11-20T11:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7728';
UPDATE tickets SET created_at = '2024-11-20T11:03:00.000Z'::timestamptz, duration_minutes = 14, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7727';
UPDATE tickets SET created_at = '2024-11-20T11:03:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7726';
UPDATE tickets SET created_at = '2024-11-16T10:05:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7714';
UPDATE tickets SET created_at = '2024-11-16T10:03:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7713';
UPDATE tickets SET created_at = '2024-11-16T10:01:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7712';
UPDATE tickets SET created_at = '2024-11-16T09:59:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7711';
UPDATE tickets SET created_at = '2024-11-16T09:58:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7710';
UPDATE tickets SET created_at = '2024-11-16T09:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7708';
UPDATE tickets SET created_at = '2024-11-14T17:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7698';
UPDATE tickets SET created_at = '2024-11-14T17:42:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7697';
UPDATE tickets SET created_at = '2024-11-14T17:41:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7695';
UPDATE tickets SET created_at = '2024-11-14T17:37:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7693';
UPDATE tickets SET created_at = '2024-11-14T17:36:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7692';
UPDATE tickets SET created_at = '2024-11-14T17:36:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7691';
UPDATE tickets SET created_at = '2024-11-14T17:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7690';
UPDATE tickets SET created_at = '2024-11-14T17:36:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7689';
UPDATE tickets SET created_at = '2024-11-14T17:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7688';
UPDATE tickets SET created_at = '2024-11-14T17:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7687';
UPDATE tickets SET created_at = '2024-11-14T17:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7686';
UPDATE tickets SET created_at = '2024-11-14T17:32:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7685';
UPDATE tickets SET created_at = '2024-11-14T17:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7684';
UPDATE tickets SET created_at = '2024-11-14T17:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7682';
UPDATE tickets SET created_at = '2024-11-14T17:27:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7680';
UPDATE tickets SET created_at = '2024-11-14T17:26:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7679';
UPDATE tickets SET created_at = '2024-11-14T17:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7678';
UPDATE tickets SET created_at = '2024-11-14T17:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7677';
UPDATE tickets SET created_at = '2024-11-14T17:23:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7676';
UPDATE tickets SET created_at = '2024-11-14T17:22:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7675';
UPDATE tickets SET created_at = '2024-11-14T17:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7674';
UPDATE tickets SET created_at = '2024-11-14T17:22:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7673';
UPDATE tickets SET created_at = '2024-11-14T17:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7672';
UPDATE tickets SET created_at = '2024-11-14T17:19:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7671';
UPDATE tickets SET created_at = '2024-11-14T17:16:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7670';
UPDATE tickets SET created_at = '2024-11-14T17:16:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7669';
UPDATE tickets SET created_at = '2024-11-14T17:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7668';
UPDATE tickets SET created_at = '2024-11-14T17:15:00.000Z'::timestamptz, duration_minutes = 44, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7667';
UPDATE tickets SET created_at = '2024-11-14T17:15:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7666';
UPDATE tickets SET created_at = '2024-11-14T17:11:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7665';
UPDATE tickets SET created_at = '2024-11-14T17:10:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7664';
UPDATE tickets SET created_at = '2024-11-14T17:10:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7663';
UPDATE tickets SET created_at = '2024-11-14T17:09:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7662';
UPDATE tickets SET created_at = '2024-11-14T17:05:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7660';
UPDATE tickets SET created_at = '2024-11-14T17:04:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7659';
UPDATE tickets SET created_at = '2024-11-14T14:48:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7653';
UPDATE tickets SET created_at = '2024-11-14T14:46:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7652';
UPDATE tickets SET created_at = '2024-11-14T14:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7651';
UPDATE tickets SET created_at = '2024-11-14T14:43:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7650';
UPDATE tickets SET created_at = '2024-11-11T10:02:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7637';
UPDATE tickets SET created_at = '2024-11-10T16:18:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7629';
UPDATE tickets SET created_at = '2024-11-10T16:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7628';
UPDATE tickets SET created_at = '2024-11-10T16:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7627';
UPDATE tickets SET created_at = '2024-11-10T16:11:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7626';
UPDATE tickets SET created_at = '2024-11-10T16:03:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7625';
UPDATE tickets SET created_at = '2024-11-10T16:01:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7624';
UPDATE tickets SET created_at = '2024-11-10T16:01:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7623';
UPDATE tickets SET created_at = '2024-11-10T16:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7622';
UPDATE tickets SET created_at = '2024-11-10T16:00:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7621';
UPDATE tickets SET created_at = '2024-11-10T16:00:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7620';
UPDATE tickets SET created_at = '2024-11-10T16:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7619';
UPDATE tickets SET created_at = '2024-11-10T15:59:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7618';
UPDATE tickets SET created_at = '2024-11-10T15:59:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7617';
UPDATE tickets SET created_at = '2024-11-10T15:58:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7616';
UPDATE tickets SET created_at = '2024-11-09T21:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7607';
UPDATE tickets SET created_at = '2024-11-09T21:34:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7606';
UPDATE tickets SET created_at = '2024-11-09T21:31:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Signaler "Server Error"' WHERE jira_issue_key = 'OBCS-7605';
UPDATE tickets SET created_at = '2024-11-09T21:28:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Signaler "Server Error"' WHERE jira_issue_key = 'OBCS-7604';
UPDATE tickets SET created_at = '2024-11-09T21:13:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7603';
UPDATE tickets SET created_at = '2024-11-09T21:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7602';
UPDATE tickets SET created_at = '2024-11-09T10:34:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7599';
UPDATE tickets SET created_at = '2024-11-09T10:34:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7598';
UPDATE tickets SET created_at = '2024-11-09T10:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7597';
UPDATE tickets SET created_at = '2024-11-09T10:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7596';
UPDATE tickets SET created_at = '2024-11-09T10:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7595';
UPDATE tickets SET created_at = '2024-11-09T10:31:00.000Z'::timestamptz, duration_minutes = 21, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7594';
UPDATE tickets SET created_at = '2024-11-09T10:29:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7593';
UPDATE tickets SET created_at = '2024-11-09T10:28:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7592';
UPDATE tickets SET created_at = '2024-11-09T10:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7591';
UPDATE tickets SET created_at = '2024-11-09T10:21:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7590';
UPDATE tickets SET created_at = '2024-11-09T10:19:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7589';
UPDATE tickets SET created_at = '2024-11-09T10:18:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7588';
UPDATE tickets SET created_at = '2024-11-09T10:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7587';
UPDATE tickets SET created_at = '2024-11-09T10:16:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7586';
UPDATE tickets SET created_at = '2024-11-09T10:15:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7585';
UPDATE tickets SET created_at = '2024-11-09T10:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7584';
UPDATE tickets SET created_at = '2024-11-09T10:12:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7583';
UPDATE tickets SET created_at = '2024-11-09T10:12:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7582';
UPDATE tickets SET created_at = '2024-11-09T10:11:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7581';
UPDATE tickets SET created_at = '2024-11-09T10:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7580';
UPDATE tickets SET created_at = '2024-11-09T10:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7579';
UPDATE tickets SET created_at = '2024-11-09T10:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7578';
UPDATE tickets SET created_at = '2024-11-08T18:42:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7577';
UPDATE tickets SET created_at = '2024-11-08T18:41:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7576';
UPDATE tickets SET created_at = '2024-11-08T18:39:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7575';
UPDATE tickets SET created_at = '2024-11-08T18:37:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7574';
UPDATE tickets SET created_at = '2024-11-08T18:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7573';
UPDATE tickets SET created_at = '2024-11-08T18:33:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7572';
UPDATE tickets SET created_at = '2024-11-08T18:31:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7571';
UPDATE tickets SET created_at = '2024-11-08T18:29:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7570';
UPDATE tickets SET created_at = '2024-11-08T18:23:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7568';
UPDATE tickets SET created_at = '2024-11-08T17:15:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7566';
UPDATE tickets SET created_at = '2024-11-08T17:15:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7565';
UPDATE tickets SET created_at = '2024-11-08T17:14:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7564';
UPDATE tickets SET created_at = '2024-11-08T17:13:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7563';
UPDATE tickets SET created_at = '2024-11-08T17:13:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7562';
UPDATE tickets SET created_at = '2024-11-08T13:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7553';
UPDATE tickets SET created_at = '2024-11-08T13:53:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7552';
UPDATE tickets SET created_at = '2024-11-08T13:53:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7551';
UPDATE tickets SET created_at = '2024-11-08T13:51:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7550';
UPDATE tickets SET created_at = '2024-11-08T13:51:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7549';
UPDATE tickets SET created_at = '2024-11-08T13:49:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7548';
UPDATE tickets SET created_at = '2024-11-08T13:48:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7547';
UPDATE tickets SET created_at = '2024-11-08T13:48:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7546';
UPDATE tickets SET created_at = '2024-11-08T13:47:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7545';
UPDATE tickets SET created_at = '2024-11-08T13:47:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7544';
UPDATE tickets SET created_at = '2024-11-08T13:44:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7543';
UPDATE tickets SET created_at = '2024-11-08T13:42:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7542';
UPDATE tickets SET created_at = '2024-11-08T13:41:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7541';
UPDATE tickets SET created_at = '2024-11-08T09:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7540';
UPDATE tickets SET created_at = '2024-11-08T09:24:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7539';
UPDATE tickets SET created_at = '2024-11-04T13:47:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7509';
UPDATE tickets SET created_at = '2024-11-03T18:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7500';
UPDATE tickets SET created_at = '2024-11-03T18:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7499';
UPDATE tickets SET created_at = '2024-11-03T18:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7498';
UPDATE tickets SET created_at = '2024-11-03T18:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7497';
UPDATE tickets SET created_at = '2024-11-02T18:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7495';
UPDATE tickets SET created_at = '2024-11-02T18:47:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7494';
UPDATE tickets SET created_at = '2024-11-02T09:34:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7484';
UPDATE tickets SET created_at = '2024-11-02T09:30:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7483';
UPDATE tickets SET created_at = '2024-11-02T09:26:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7482';
UPDATE tickets SET created_at = '2024-10-31T17:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7478';
UPDATE tickets SET created_at = '2024-10-31T12:14:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7466';
UPDATE tickets SET created_at = '2024-10-31T12:12:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7465';
UPDATE tickets SET created_at = '2024-10-31T12:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7464';
UPDATE tickets SET created_at = '2024-10-31T12:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7463';
UPDATE tickets SET created_at = '2024-10-31T12:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7462';
UPDATE tickets SET created_at = '2024-10-31T12:04:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7461';
UPDATE tickets SET created_at = '2024-10-31T12:04:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7460';
UPDATE tickets SET created_at = '2024-10-31T12:02:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7459';
UPDATE tickets SET created_at = '2024-10-31T12:02:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7458';
UPDATE tickets SET created_at = '2024-10-31T12:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7457';
UPDATE tickets SET created_at = '2024-10-30T20:15:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7451';
UPDATE tickets SET created_at = '2024-10-30T20:13:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7450';
UPDATE tickets SET created_at = '2024-10-30T20:12:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7449';
UPDATE tickets SET created_at = '2024-10-30T20:11:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7448';
UPDATE tickets SET created_at = '2024-10-30T20:10:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7447';
UPDATE tickets SET created_at = '2024-10-30T20:10:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7446';
UPDATE tickets SET created_at = '2024-10-27T14:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7415';
UPDATE tickets SET created_at = '2024-10-27T14:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7414';
UPDATE tickets SET created_at = '2024-10-27T14:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7413';
UPDATE tickets SET created_at = '2024-10-27T14:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7412';
UPDATE tickets SET created_at = '2024-10-27T14:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7411';
UPDATE tickets SET created_at = '2024-10-27T14:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7410';
UPDATE tickets SET created_at = '2024-10-27T14:20:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7409';
UPDATE tickets SET created_at = '2024-10-27T14:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7408';
UPDATE tickets SET created_at = '2024-10-27T14:07:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7407';
UPDATE tickets SET created_at = '2024-10-27T14:07:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7406';
UPDATE tickets SET created_at = '2024-10-27T14:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7405';
UPDATE tickets SET created_at = '2024-10-27T14:04:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7404';
UPDATE tickets SET created_at = '2024-10-27T14:04:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7403';
UPDATE tickets SET created_at = '2024-10-27T14:02:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7402';
UPDATE tickets SET created_at = '2024-10-27T10:35:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7401';
UPDATE tickets SET created_at = '2024-10-27T10:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7400';
UPDATE tickets SET created_at = '2024-10-27T10:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7398';
UPDATE tickets SET created_at = '2024-10-27T10:20:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7397';
UPDATE tickets SET created_at = '2024-10-26T21:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7396';
UPDATE tickets SET created_at = '2024-10-26T21:01:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7395';
UPDATE tickets SET created_at = '2024-10-26T21:01:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7394';
UPDATE tickets SET created_at = '2024-10-26T20:59:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7393';
UPDATE tickets SET created_at = '2024-10-26T20:58:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7392';
UPDATE tickets SET created_at = '2024-10-26T20:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7391';
UPDATE tickets SET created_at = '2024-10-26T20:52:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7390';
UPDATE tickets SET created_at = '2024-10-26T20:50:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7389';
UPDATE tickets SET created_at = '2024-10-26T20:48:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7388';
UPDATE tickets SET created_at = '2024-10-26T20:48:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7387';
UPDATE tickets SET created_at = '2024-10-26T20:47:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7386';
UPDATE tickets SET created_at = '2024-10-26T20:39:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7385';
UPDATE tickets SET created_at = '2024-10-26T20:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7384';
UPDATE tickets SET created_at = '2024-10-26T20:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7383';
UPDATE tickets SET created_at = '2024-10-26T19:51:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7367';
UPDATE tickets SET created_at = '2024-10-26T19:49:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7366';
UPDATE tickets SET created_at = '2024-10-26T19:44:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7365';
UPDATE tickets SET created_at = '2024-10-26T19:37:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7364';
UPDATE tickets SET created_at = '2024-10-26T19:35:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7363';
UPDATE tickets SET created_at = '2024-10-26T19:25:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7362';
UPDATE tickets SET created_at = '2024-10-26T19:22:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7361';
UPDATE tickets SET created_at = '2024-10-26T19:20:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7360';
UPDATE tickets SET created_at = '2024-10-24T18:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7356';
UPDATE tickets SET created_at = '2024-10-24T18:52:00.000Z'::timestamptz, duration_minutes = 6 WHERE jira_issue_key = 'OBCS-7355';
UPDATE tickets SET created_at = '2024-10-24T18:50:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7354';
UPDATE tickets SET created_at = '2024-10-24T18:49:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7353';
UPDATE tickets SET created_at = '2024-10-24T18:49:00.000Z'::timestamptz, duration_minutes = 23, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7352';
UPDATE tickets SET created_at = '2024-10-21T18:07:00.000Z'::timestamptz, duration_minutes = 60, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7341';
UPDATE tickets SET created_at = '2024-10-21T18:07:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7340';
UPDATE tickets SET created_at = '2024-10-21T18:06:00.000Z'::timestamptz, duration_minutes = 18, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7339';
UPDATE tickets SET created_at = '2024-10-21T18:04:00.000Z'::timestamptz, duration_minutes = 60, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7338';
UPDATE tickets SET created_at = '2024-10-21T18:03:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7337';
UPDATE tickets SET created_at = '2024-10-21T18:02:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7336';
UPDATE tickets SET created_at = '2024-10-21T18:02:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7335';
UPDATE tickets SET created_at = '2024-10-20T14:45:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7327';
UPDATE tickets SET created_at = '2024-10-20T14:44:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7326';
UPDATE tickets SET created_at = '2024-10-20T14:41:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7325';
UPDATE tickets SET created_at = '2024-10-20T14:40:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7324';
UPDATE tickets SET created_at = '2024-10-20T14:38:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7323';
UPDATE tickets SET created_at = '2024-10-20T14:36:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7322';
UPDATE tickets SET created_at = '2024-10-20T14:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7321';
UPDATE tickets SET created_at = '2024-10-20T14:35:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7320';
UPDATE tickets SET created_at = '2024-10-18T20:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7319';
UPDATE tickets SET created_at = '2024-10-18T20:18:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7318';
UPDATE tickets SET created_at = '2024-10-18T19:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7317';
UPDATE tickets SET created_at = '2024-10-18T19:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7316';
UPDATE tickets SET created_at = '2024-10-18T19:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7315';
UPDATE tickets SET created_at = '2024-10-18T19:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7313';
UPDATE tickets SET created_at = '2024-10-18T19:15:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7312';
UPDATE tickets SET created_at = '2024-10-18T19:13:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7311';
UPDATE tickets SET created_at = '2024-10-18T17:01:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7310';
UPDATE tickets SET created_at = '2024-10-18T16:45:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7309';
UPDATE tickets SET created_at = '2024-10-18T16:25:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7308';
UPDATE tickets SET created_at = '2024-10-18T16:23:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7307';
UPDATE tickets SET created_at = '2024-10-18T16:21:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7306';
UPDATE tickets SET created_at = '2024-10-18T14:40:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7301';
UPDATE tickets SET created_at = '2024-10-18T14:39:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7300';
UPDATE tickets SET created_at = '2024-10-18T14:39:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7299';
UPDATE tickets SET created_at = '2024-10-18T09:55:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7297';
UPDATE tickets SET created_at = '2024-10-18T09:54:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7296';
UPDATE tickets SET created_at = '2024-10-18T09:51:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7295';
UPDATE tickets SET created_at = '2024-10-18T09:47:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7294';
UPDATE tickets SET created_at = '2024-10-18T09:37:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7293';
UPDATE tickets SET created_at = '2024-10-18T09:23:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7292';
UPDATE tickets SET created_at = '2024-10-17T21:10:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7290';
UPDATE tickets SET created_at = '2024-10-17T21:10:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7289';
UPDATE tickets SET created_at = '2024-10-17T21:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7288';
UPDATE tickets SET created_at = '2024-10-17T21:08:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7287';
UPDATE tickets SET created_at = '2024-10-17T21:06:00.000Z'::timestamptz, duration_minutes = 6 WHERE jira_issue_key = 'OBCS-7286';
UPDATE tickets SET created_at = '2024-10-17T21:06:00.000Z'::timestamptz, duration_minutes = 3 WHERE jira_issue_key = 'OBCS-7285';
UPDATE tickets SET created_at = '2024-10-17T21:05:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7284';
UPDATE tickets SET created_at = '2024-10-17T21:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7283';
UPDATE tickets SET created_at = '2024-10-17T20:59:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7282';
UPDATE tickets SET created_at = '2024-10-17T20:58:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7281';
UPDATE tickets SET created_at = '2024-10-17T20:58:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7280';
UPDATE tickets SET created_at = '2024-10-17T20:57:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7279';
UPDATE tickets SET created_at = '2024-10-17T20:56:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7278';
UPDATE tickets SET created_at = '2024-10-17T20:55:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7277';
UPDATE tickets SET created_at = '2024-10-17T20:54:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7276';
UPDATE tickets SET created_at = '2024-10-13T16:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7248';
UPDATE tickets SET created_at = '2024-10-13T16:23:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7247';
UPDATE tickets SET created_at = '2024-10-13T16:20:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7246';
UPDATE tickets SET created_at = '2024-10-13T16:20:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7245';
UPDATE tickets SET created_at = '2024-10-13T16:17:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7244';
UPDATE tickets SET created_at = '2024-10-13T16:16:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7243';
UPDATE tickets SET created_at = '2024-10-13T16:15:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7242';
UPDATE tickets SET created_at = '2024-10-13T16:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7241';
UPDATE tickets SET created_at = '2024-10-13T16:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7240';
UPDATE tickets SET created_at = '2024-10-13T16:13:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7239';
UPDATE tickets SET created_at = '2024-10-13T16:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7238';
UPDATE tickets SET created_at = '2024-10-13T16:07:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7237';
UPDATE tickets SET created_at = '2024-10-13T16:06:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7236';
UPDATE tickets SET created_at = '2024-10-13T16:05:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7235';
UPDATE tickets SET created_at = '2024-10-13T16:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7234';
UPDATE tickets SET created_at = '2024-10-13T16:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7233';
UPDATE tickets SET created_at = '2024-10-13T16:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7232';
UPDATE tickets SET created_at = '2024-10-13T16:04:00.000Z'::timestamptz, duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7231';
UPDATE tickets SET created_at = '2024-10-13T16:03:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7230';
UPDATE tickets SET created_at = '2024-10-13T16:03:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7229';
UPDATE tickets SET created_at = '2024-10-13T15:59:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7228';
UPDATE tickets SET created_at = '2024-10-13T15:40:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7227';
UPDATE tickets SET created_at = '2024-10-13T15:39:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7226';
UPDATE tickets SET created_at = '2024-10-13T15:39:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7225';
UPDATE tickets SET created_at = '2024-10-13T15:37:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7224';
UPDATE tickets SET created_at = '2024-10-13T15:37:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7223';
UPDATE tickets SET created_at = '2024-10-13T07:35:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7222';
UPDATE tickets SET created_at = '2024-10-13T07:31:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-7221';
UPDATE tickets SET created_at = '2024-10-13T07:29:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7220';
UPDATE tickets SET created_at = '2024-10-13T07:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7219';
UPDATE tickets SET created_at = '2024-10-13T07:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7218';
UPDATE tickets SET created_at = '2024-10-12T21:47:00.000Z'::timestamptz, duration_minutes = 14, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7211';
UPDATE tickets SET created_at = '2024-10-12T21:47:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7210';
UPDATE tickets SET created_at = '2024-10-12T21:46:00.000Z'::timestamptz, duration_minutes = 19, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7209';
UPDATE tickets SET created_at = '2024-10-12T21:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7208';
UPDATE tickets SET created_at = '2024-10-12T21:43:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7207';
UPDATE tickets SET created_at = '2024-10-12T21:42:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7206';
UPDATE tickets SET created_at = '2024-10-12T21:41:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7205';
UPDATE tickets SET created_at = '2024-10-12T21:40:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7204';
UPDATE tickets SET created_at = '2024-10-12T21:40:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7203';
