-- OnpointDoc - Mise à jour des tickets d'assistance depuis l'export JIRA (PARTIE 5)
-- Date: 2025-12-10
-- Description: Met à jour created_at, duration_minutes, action_menee et objet_principal
-- Partie 5 sur 15 (500 tickets)

UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8913';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8912';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8910';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8909';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8908';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8907';
UPDATE tickets SET duration_minutes = 60 WHERE jira_issue_key = 'OBCS-8897';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8896';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8895';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8894';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8893';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8892';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8891';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8890';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8889';
UPDATE tickets SET duration_minutes = 30 WHERE jira_issue_key = 'OBCS-8888';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8879';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8878';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8877';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8876';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8875';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8874';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8873';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8872';
UPDATE tickets SET duration_minutes = 1 WHERE jira_issue_key = 'OBCS-8871';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8870';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-8869';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8868';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8867';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8866';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8865';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8864';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8863';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Revue des Accès/Workflows', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8862';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Revue des Accès/Workflows', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8861';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Revue des Accès/Workflows', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8860';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Revue des Accès/Workflows', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8859';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Revue des Accès/Workflows', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8858';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8857';
UPDATE tickets SET duration_minutes = 1 WHERE jira_issue_key = 'OBCS-8856';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-8855';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8854';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8853';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8852';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8851';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8848';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8847';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8846';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8845';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8844';
UPDATE tickets SET duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8843';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8842';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8841';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8840';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8839';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8838';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8837';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8835';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8834';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8833';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8832';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8831';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8830';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8816';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8815';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8814';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8813';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8812';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8811';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8810';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8809';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8808';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8807';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8806';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8805';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8804';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8803';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8802';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8801';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8800';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8799';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8798';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8797';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8796';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8795';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8794';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8793';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8792';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8791';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8790';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8789';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8788';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8787';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8786';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8785';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8784';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8783';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8782';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8780';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8779';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8739';
UPDATE tickets SET duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8738';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8737';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8736';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8735';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8734';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8733';
UPDATE tickets SET duration_minutes = 19, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8732';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8731';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8730';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8729';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8728';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8727';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8726';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8725';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8724';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8723';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8722';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8721';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8720';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8719';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8718';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8717';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8716';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8715';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8714';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8713';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8712';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8711';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8710';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8709';
UPDATE tickets SET duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8703';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8702';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8701';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8700';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8699';
UPDATE tickets SET duration_minutes = 6 WHERE jira_issue_key = 'OBCS-8698';
UPDATE tickets SET duration_minutes = 6 WHERE jira_issue_key = 'OBCS-8697';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8696';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8695';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8694';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8693';
UPDATE tickets SET created_at = '2025-01-31T18:32:00.000Z'::timestamptz, duration_minutes = 25, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8692';
UPDATE tickets SET created_at = '2025-01-31T18:32:00.000Z'::timestamptz, duration_minutes = 25, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8691';
UPDATE tickets SET created_at = '2025-01-31T18:31:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8690';
UPDATE tickets SET created_at = '2025-01-31T18:31:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8689';
UPDATE tickets SET created_at = '2025-01-31T18:29:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8688';
UPDATE tickets SET created_at = '2025-01-31T18:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8687';
UPDATE tickets SET created_at = '2025-01-31T18:28:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8686';
UPDATE tickets SET created_at = '2025-01-31T18:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8685';
UPDATE tickets SET created_at = '2025-01-31T18:27:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8684';
UPDATE tickets SET created_at = '2025-01-31T18:25:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8683';
UPDATE tickets SET created_at = '2025-01-31T18:25:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8682';
UPDATE tickets SET created_at = '2025-01-31T18:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8681';
UPDATE tickets SET created_at = '2025-01-31T18:20:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8680';
UPDATE tickets SET created_at = '2025-01-31T18:19:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8679';
UPDATE tickets SET created_at = '2025-01-31T18:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8678';
UPDATE tickets SET created_at = '2025-01-31T18:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8677';
UPDATE tickets SET created_at = '2025-01-31T18:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8676';
UPDATE tickets SET created_at = '2025-01-31T18:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8675';
UPDATE tickets SET created_at = '2025-01-31T11:41:00.000Z'::timestamptz, duration_minutes = 120 WHERE jira_issue_key = 'OBCS-8663';
UPDATE tickets SET created_at = '2025-01-26T13:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8629';
UPDATE tickets SET created_at = '2025-01-26T13:25:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8628';
UPDATE tickets SET created_at = '2025-01-26T13:24:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8627';
UPDATE tickets SET created_at = '2025-01-26T13:23:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8626';
UPDATE tickets SET created_at = '2025-01-26T13:22:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8625';
UPDATE tickets SET created_at = '2025-01-26T13:21:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8624';
UPDATE tickets SET created_at = '2025-01-26T13:21:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8623';
UPDATE tickets SET created_at = '2025-01-26T13:20:00.000Z'::timestamptz, duration_minutes = 45, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8622';
UPDATE tickets SET created_at = '2025-01-26T13:19:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8621';
UPDATE tickets SET created_at = '2025-01-26T13:18:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8620';
UPDATE tickets SET created_at = '2025-01-26T13:18:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8619';
UPDATE tickets SET created_at = '2025-01-26T13:18:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8618';
UPDATE tickets SET created_at = '2025-01-26T13:18:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8617';
UPDATE tickets SET created_at = '2025-01-26T13:16:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8616';
UPDATE tickets SET created_at = '2025-01-26T13:16:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8615';
UPDATE tickets SET created_at = '2025-01-26T13:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8614';
UPDATE tickets SET created_at = '2025-01-26T13:14:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8613';
UPDATE tickets SET created_at = '2025-01-26T13:10:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8612';
UPDATE tickets SET created_at = '2025-01-26T13:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8611';
UPDATE tickets SET created_at = '2025-01-26T13:09:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8610';
UPDATE tickets SET created_at = '2025-01-26T13:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8609';
UPDATE tickets SET created_at = '2025-01-25T15:09:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8608';
UPDATE tickets SET created_at = '2025-01-25T15:07:00.000Z'::timestamptz, duration_minutes = 51, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8607';
UPDATE tickets SET created_at = '2025-01-25T14:59:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8606';
UPDATE tickets SET created_at = '2025-01-25T14:57:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8605';
UPDATE tickets SET created_at = '2025-01-25T14:55:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8604';
UPDATE tickets SET created_at = '2025-01-25T14:54:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8603';
UPDATE tickets SET created_at = '2025-01-25T14:53:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8602';
UPDATE tickets SET created_at = '2025-01-25T14:52:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8601';
UPDATE tickets SET created_at = '2025-01-25T14:52:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8600';
UPDATE tickets SET created_at = '2025-01-25T14:51:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8599';
UPDATE tickets SET created_at = '2025-01-25T14:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8596';
UPDATE tickets SET created_at = '2025-01-25T14:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8595';
UPDATE tickets SET created_at = '2025-01-25T13:49:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8594';
UPDATE tickets SET created_at = '2025-01-25T13:44:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8593';
UPDATE tickets SET created_at = '2025-01-25T13:36:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8592';
UPDATE tickets SET created_at = '2025-01-25T13:35:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8591';
UPDATE tickets SET created_at = '2025-01-25T13:34:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8590';
UPDATE tickets SET created_at = '2025-01-25T13:33:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8589';
UPDATE tickets SET created_at = '2025-01-25T13:13:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8588';
UPDATE tickets SET created_at = '2025-01-25T13:02:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8587';
UPDATE tickets SET created_at = '2025-01-25T12:48:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8586';
UPDATE tickets SET created_at = '2025-01-25T12:41:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8585';
UPDATE tickets SET created_at = '2025-01-25T12:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8584';
UPDATE tickets SET created_at = '2025-01-25T12:13:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8583';
UPDATE tickets SET created_at = '2025-01-25T09:56:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8582';
UPDATE tickets SET created_at = '2025-01-25T09:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8581';
UPDATE tickets SET created_at = '2025-01-25T09:54:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8580';
UPDATE tickets SET created_at = '2025-01-25T09:52:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8579';
UPDATE tickets SET created_at = '2025-01-25T09:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8578';
UPDATE tickets SET created_at = '2025-01-25T09:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8577';
UPDATE tickets SET created_at = '2025-01-25T09:30:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8576';
UPDATE tickets SET created_at = '2025-01-25T09:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8575';
UPDATE tickets SET created_at = '2025-01-25T09:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8574';
UPDATE tickets SET created_at = '2025-01-25T09:26:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8573';
UPDATE tickets SET created_at = '2025-01-25T09:25:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8572';
UPDATE tickets SET created_at = '2025-01-25T09:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8571';
UPDATE tickets SET created_at = '2025-01-25T09:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8570';
UPDATE tickets SET created_at = '2025-01-25T09:22:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8569';
UPDATE tickets SET created_at = '2025-01-25T09:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8568';
UPDATE tickets SET created_at = '2025-01-25T09:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8567';
UPDATE tickets SET created_at = '2025-01-25T09:20:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8566';
UPDATE tickets SET created_at = '2025-01-25T09:18:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8565';
UPDATE tickets SET created_at = '2025-01-24T22:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8554';
UPDATE tickets SET created_at = '2025-01-24T22:33:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8553';
UPDATE tickets SET created_at = '2025-01-24T22:33:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8552';
UPDATE tickets SET created_at = '2025-01-24T22:30:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8551';
UPDATE tickets SET created_at = '2025-01-24T22:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8550';
UPDATE tickets SET created_at = '2025-01-24T22:28:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8549';
UPDATE tickets SET created_at = '2025-01-24T22:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8548';
UPDATE tickets SET created_at = '2025-01-24T22:27:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8547';
UPDATE tickets SET created_at = '2025-01-24T22:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8546';
UPDATE tickets SET created_at = '2025-01-24T22:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8545';
UPDATE tickets SET created_at = '2025-01-24T22:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8544';
UPDATE tickets SET created_at = '2025-01-24T22:22:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8543';
UPDATE tickets SET created_at = '2025-01-24T22:21:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8542';
UPDATE tickets SET created_at = '2025-01-24T22:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8541';
UPDATE tickets SET created_at = '2025-01-24T22:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8540';
UPDATE tickets SET created_at = '2025-01-24T10:39:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8538';
UPDATE tickets SET created_at = '2025-01-24T08:38:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8537';
UPDATE tickets SET created_at = '2025-01-24T08:33:00.000Z'::timestamptz, duration_minutes = 3 WHERE jira_issue_key = 'OBCS-8536';
UPDATE tickets SET created_at = '2025-01-20T08:30:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8528';
UPDATE tickets SET created_at = '2025-01-20T08:29:00.000Z'::timestamptz, duration_minutes = 66, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8527';
UPDATE tickets SET created_at = '2025-01-19T16:29:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8525';
UPDATE tickets SET created_at = '2025-01-19T16:29:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8524';
UPDATE tickets SET created_at = '2025-01-19T15:49:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8515';
UPDATE tickets SET created_at = '2025-01-19T15:49:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8514';
UPDATE tickets SET created_at = '2025-01-19T15:48:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8513';
UPDATE tickets SET created_at = '2025-01-19T15:48:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8512';
UPDATE tickets SET created_at = '2025-01-19T15:47:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8511';
UPDATE tickets SET created_at = '2025-01-19T15:46:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8510';
UPDATE tickets SET created_at = '2025-01-19T15:46:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8509';
UPDATE tickets SET created_at = '2025-01-19T13:49:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8508';
UPDATE tickets SET created_at = '2025-01-19T13:47:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8507';
UPDATE tickets SET created_at = '2025-01-19T13:43:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8506';
UPDATE tickets SET created_at = '2025-01-18T07:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8505';
UPDATE tickets SET created_at = '2025-01-18T07:20:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8504';
UPDATE tickets SET created_at = '2025-01-18T07:17:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8503';
UPDATE tickets SET created_at = '2025-01-18T02:14:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8502';
UPDATE tickets SET created_at = '2025-01-18T02:12:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8501';
UPDATE tickets SET created_at = '2025-01-18T02:00:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8498';
UPDATE tickets SET created_at = '2025-01-17T15:16:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8497';
UPDATE tickets SET created_at = '2025-01-17T15:15:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8496';
UPDATE tickets SET created_at = '2025-01-17T14:57:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8495';
UPDATE tickets SET created_at = '2025-01-17T14:57:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8494';
UPDATE tickets SET created_at = '2025-01-17T14:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8493';
UPDATE tickets SET created_at = '2025-01-17T14:52:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8492';
UPDATE tickets SET created_at = '2025-01-17T14:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8491';
UPDATE tickets SET created_at = '2025-01-17T12:48:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8490';
UPDATE tickets SET created_at = '2025-01-17T12:47:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8489';
UPDATE tickets SET created_at = '2025-01-17T12:46:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8488';
UPDATE tickets SET created_at = '2025-01-17T12:46:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8487';
UPDATE tickets SET created_at = '2025-01-17T12:46:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8486';
UPDATE tickets SET created_at = '2025-01-17T12:46:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8485';
UPDATE tickets SET created_at = '2025-01-17T12:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8484';
UPDATE tickets SET created_at = '2025-01-17T12:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8483';
UPDATE tickets SET created_at = '2025-01-17T12:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8482';
UPDATE tickets SET created_at = '2025-01-17T12:44:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8481';
UPDATE tickets SET created_at = '2025-01-17T12:40:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8480';
UPDATE tickets SET created_at = '2025-01-17T12:39:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8479';
UPDATE tickets SET created_at = '2025-01-17T12:39:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8478';
UPDATE tickets SET created_at = '2025-01-17T12:36:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8477';
UPDATE tickets SET created_at = '2025-01-17T12:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8476';
UPDATE tickets SET created_at = '2025-01-17T12:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8475';
UPDATE tickets SET created_at = '2025-01-17T12:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8474';
UPDATE tickets SET created_at = '2025-01-17T12:34:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8473';
UPDATE tickets SET created_at = '2025-01-17T12:34:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8472';
UPDATE tickets SET created_at = '2025-01-17T12:27:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8471';
UPDATE tickets SET created_at = '2025-01-17T12:27:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8470';
UPDATE tickets SET created_at = '2025-01-17T12:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8469';
UPDATE tickets SET created_at = '2025-01-17T12:27:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8468';
UPDATE tickets SET created_at = '2025-01-17T12:26:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8467';
UPDATE tickets SET created_at = '2025-01-17T12:26:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8466';
UPDATE tickets SET created_at = '2025-01-17T12:25:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8465';
UPDATE tickets SET created_at = '2025-01-17T12:25:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8464';
UPDATE tickets SET created_at = '2025-01-17T12:24:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8463';
UPDATE tickets SET created_at = '2025-01-17T12:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8462';
UPDATE tickets SET created_at = '2025-01-17T12:23:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8461';
UPDATE tickets SET created_at = '2025-01-17T12:15:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8459';
UPDATE tickets SET created_at = '2025-01-17T12:14:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8458';
UPDATE tickets SET created_at = '2025-01-17T12:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8457';
UPDATE tickets SET created_at = '2025-01-17T12:12:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8456';
UPDATE tickets SET created_at = '2025-01-17T12:12:00.000Z'::timestamptz, duration_minutes = 8 WHERE jira_issue_key = 'OBCS-8455';
UPDATE tickets SET created_at = '2025-01-17T12:09:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8454';
UPDATE tickets SET created_at = '2025-01-17T12:08:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8453';
UPDATE tickets SET created_at = '2025-01-17T12:07:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8452';
UPDATE tickets SET created_at = '2025-01-15T11:27:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8437';
UPDATE tickets SET created_at = '2025-01-15T11:26:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8436';
UPDATE tickets SET created_at = '2025-01-15T11:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8435';
UPDATE tickets SET created_at = '2025-01-15T11:23:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8434';
UPDATE tickets SET created_at = '2025-01-15T11:21:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8433';
UPDATE tickets SET created_at = '2025-01-15T11:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8432';
UPDATE tickets SET created_at = '2025-01-15T11:20:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8431';
UPDATE tickets SET created_at = '2025-01-15T11:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8430';
UPDATE tickets SET created_at = '2025-01-13T14:13:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8418';
UPDATE tickets SET created_at = '2025-01-12T18:56:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8411';
UPDATE tickets SET created_at = '2025-01-12T18:55:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8410';
UPDATE tickets SET created_at = '2025-01-11T19:15:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8409';
UPDATE tickets SET created_at = '2025-01-11T19:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8408';
UPDATE tickets SET created_at = '2025-01-11T19:13:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8407';
UPDATE tickets SET created_at = '2025-01-11T19:11:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8406';
UPDATE tickets SET created_at = '2025-01-11T19:09:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8405';
UPDATE tickets SET created_at = '2025-01-11T18:58:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8404';
UPDATE tickets SET created_at = '2025-01-11T18:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8403';
UPDATE tickets SET created_at = '2025-01-11T18:55:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8402';
UPDATE tickets SET created_at = '2025-01-11T18:52:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8401';
UPDATE tickets SET created_at = '2025-01-11T18:51:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8400';
UPDATE tickets SET created_at = '2025-01-11T18:50:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8399';
UPDATE tickets SET created_at = '2025-01-11T18:49:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8398';
UPDATE tickets SET created_at = '2025-01-11T18:45:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8397';
UPDATE tickets SET created_at = '2025-01-11T18:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8396';
UPDATE tickets SET created_at = '2025-01-11T18:44:00.000Z'::timestamptz, duration_minutes = 18, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8395';
UPDATE tickets SET created_at = '2025-01-11T18:44:00.000Z'::timestamptz, duration_minutes = 18, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8394';
UPDATE tickets SET created_at = '2025-01-11T18:43:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8393';
UPDATE tickets SET created_at = '2025-01-11T18:40:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8392';
UPDATE tickets SET created_at = '2025-01-11T18:39:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8391';
UPDATE tickets SET created_at = '2025-01-11T15:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8387';
UPDATE tickets SET created_at = '2025-01-11T15:50:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8386';
UPDATE tickets SET created_at = '2025-01-11T15:47:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8385';
UPDATE tickets SET created_at = '2025-01-11T15:44:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8384';
UPDATE tickets SET created_at = '2025-01-11T15:41:00.000Z'::timestamptz, duration_minutes = 26, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8383';
UPDATE tickets SET created_at = '2025-01-11T15:37:00.000Z'::timestamptz, duration_minutes = 25, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8382';
UPDATE tickets SET created_at = '2025-01-11T15:35:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8381';
UPDATE tickets SET created_at = '2025-01-11T15:33:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8380';
UPDATE tickets SET created_at = '2025-01-10T18:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8378';
UPDATE tickets SET created_at = '2025-01-10T18:09:00.000Z'::timestamptz, duration_minutes = 22, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8377';
UPDATE tickets SET created_at = '2025-01-10T18:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8376';
UPDATE tickets SET created_at = '2025-01-10T18:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8375';
UPDATE tickets SET created_at = '2025-01-10T18:07:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8374';
UPDATE tickets SET created_at = '2025-01-10T18:05:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8373';
UPDATE tickets SET created_at = '2025-01-10T18:03:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8372';
UPDATE tickets SET created_at = '2025-01-10T18:03:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8371';
UPDATE tickets SET created_at = '2025-01-10T18:03:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8370';
UPDATE tickets SET created_at = '2025-01-10T18:03:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8369';
UPDATE tickets SET created_at = '2025-01-10T18:02:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8368';
UPDATE tickets SET created_at = '2025-01-10T18:02:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8367';
UPDATE tickets SET created_at = '2025-01-10T18:02:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8366';
UPDATE tickets SET created_at = '2025-01-10T18:01:00.000Z'::timestamptz, duration_minutes = 14, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8365';
UPDATE tickets SET created_at = '2025-01-10T18:01:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8364';
UPDATE tickets SET created_at = '2025-01-10T17:59:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8363';
UPDATE tickets SET created_at = '2025-01-10T17:59:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8362';
UPDATE tickets SET created_at = '2025-01-10T17:56:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8361';
UPDATE tickets SET created_at = '2025-01-10T17:55:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8360';
UPDATE tickets SET created_at = '2025-01-10T17:55:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8359';
UPDATE tickets SET created_at = '2025-01-10T17:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8358';
UPDATE tickets SET created_at = '2025-01-10T17:54:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8357';
UPDATE tickets SET created_at = '2025-01-10T17:54:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8356';
UPDATE tickets SET created_at = '2025-01-10T17:53:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8355';
UPDATE tickets SET created_at = '2025-01-10T17:52:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8354';
UPDATE tickets SET created_at = '2025-01-10T17:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8353';
UPDATE tickets SET created_at = '2025-01-10T17:50:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8352';
UPDATE tickets SET created_at = '2025-01-10T17:50:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8351';
UPDATE tickets SET created_at = '2025-01-10T17:50:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8350';
UPDATE tickets SET created_at = '2025-01-10T17:49:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8349';
UPDATE tickets SET created_at = '2025-01-10T17:46:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8348';
UPDATE tickets SET created_at = '2025-01-10T17:46:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8347';
UPDATE tickets SET created_at = '2025-01-10T17:43:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8346';
UPDATE tickets SET created_at = '2025-01-10T17:42:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8345';
UPDATE tickets SET created_at = '2025-01-10T17:41:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8344';
UPDATE tickets SET created_at = '2025-01-10T17:41:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8343';
UPDATE tickets SET created_at = '2025-01-06T15:30:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8320';
UPDATE tickets SET created_at = '2025-01-04T16:13:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8313';
UPDATE tickets SET created_at = '2025-01-04T16:11:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8312';
UPDATE tickets SET created_at = '2025-01-04T16:09:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8311';
UPDATE tickets SET created_at = '2025-01-04T16:07:00.000Z'::timestamptz, duration_minutes = 205, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8310';
UPDATE tickets SET created_at = '2025-01-04T16:03:00.000Z'::timestamptz, duration_minutes = 16, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8309';
UPDATE tickets SET created_at = '2025-01-04T16:02:00.000Z'::timestamptz, duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8308';
UPDATE tickets SET created_at = '2025-01-04T16:00:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8307';
UPDATE tickets SET created_at = '2025-01-04T15:59:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8306';
UPDATE tickets SET created_at = '2025-01-04T15:56:00.000Z'::timestamptz, duration_minutes = 17, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8305';
UPDATE tickets SET created_at = '2025-01-04T14:26:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8304';
UPDATE tickets SET created_at = '2025-01-04T14:25:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8303';
UPDATE tickets SET created_at = '2025-01-04T14:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8302';
UPDATE tickets SET created_at = '2025-01-04T11:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8300';
UPDATE tickets SET created_at = '2025-01-04T11:00:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8299';
UPDATE tickets SET created_at = '2025-01-04T10:59:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8298';
UPDATE tickets SET created_at = '2025-01-04T10:51:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8297';
UPDATE tickets SET created_at = '2025-01-04T10:50:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8296';
UPDATE tickets SET created_at = '2025-01-04T10:50:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8295';
UPDATE tickets SET created_at = '2025-01-04T10:49:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8294';
UPDATE tickets SET created_at = '2025-01-04T10:49:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8293';
UPDATE tickets SET created_at = '2025-01-04T10:49:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8292';
UPDATE tickets SET created_at = '2025-01-04T10:48:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8291';
UPDATE tickets SET created_at = '2025-01-04T10:46:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8290';
UPDATE tickets SET created_at = '2025-01-04T10:45:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8289';
UPDATE tickets SET created_at = '2025-01-04T10:44:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8288';
UPDATE tickets SET created_at = '2025-01-04T10:44:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8287';
UPDATE tickets SET created_at = '2025-01-04T10:43:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8286';
UPDATE tickets SET created_at = '2025-01-04T10:43:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8285';
UPDATE tickets SET created_at = '2025-01-03T12:45:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8273';
UPDATE tickets SET created_at = '2025-01-03T12:44:00.000Z'::timestamptz, duration_minutes = 8 WHERE jira_issue_key = 'OBCS-8272';
UPDATE tickets SET created_at = '2025-01-03T12:42:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8271';
UPDATE tickets SET created_at = '2025-01-02T11:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8264';
UPDATE tickets SET created_at = '2025-01-02T11:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8263';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8259';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8255';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8254';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8253';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8252';
UPDATE tickets SET duration_minutes = 16, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8251';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8250';
UPDATE tickets SET duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8249';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8248';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8247';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8246';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8245';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8244';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8243';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8242';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8241';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8240';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8239';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8238';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8237';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8236';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8235';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8227';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8226';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8218';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8217';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8216';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8215';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8214';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8207';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8206';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8205';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8204';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8203';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8202';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8201';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8200';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8195';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8194';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8193';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8192';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8191';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8190';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8189';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-8188';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8187';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8185';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8184';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8183';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8182';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-8181';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8180';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8179';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8178';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-8177';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8168';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8167';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8166';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8165';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8164';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8163';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8153';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8152';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8151';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8150';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8148';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8137';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8136';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-8135';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8134';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8133';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8132';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8131';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-8130';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8129';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-8128';
UPDATE tickets SET duration_minutes = 5 WHERE jira_issue_key = 'OBCS-8127';
UPDATE tickets SET duration_minutes = 5 WHERE jira_issue_key = 'OBCS-8126';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8125';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8124';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8123';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8122';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8116';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8115';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-8114';
