-- OnpointDoc - Mise à jour des tickets d'assistance depuis l'export JIRA (PARTIE 2)
-- Date: 2025-12-10
-- Description: Met à jour created_at, duration_minutes, action_menee et objet_principal
-- Partie 2 sur 15 (500 tickets)

UPDATE tickets SET created_at = '2025-10-18T14:39:00.000Z'::timestamptz, duration_minutes = 5 WHERE jira_issue_key = 'OBCS-11390';
UPDATE tickets SET created_at = '2025-10-18T14:39:00.000Z'::timestamptz, duration_minutes = 2 WHERE jira_issue_key = 'OBCS-11389';
UPDATE tickets SET created_at = '2025-10-18T14:32:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11388';
UPDATE tickets SET created_at = '2025-10-18T14:31:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11387';
UPDATE tickets SET created_at = '2025-10-18T14:25:00.000Z'::timestamptz, duration_minutes = 23, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11386';
UPDATE tickets SET created_at = '2025-10-18T14:21:00.000Z'::timestamptz, duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11385';
UPDATE tickets SET created_at = '2025-10-18T10:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11384';
UPDATE tickets SET created_at = '2025-10-17T18:25:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11371';
UPDATE tickets SET created_at = '2025-10-17T18:25:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11370';
UPDATE tickets SET created_at = '2025-10-17T18:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11369';
UPDATE tickets SET created_at = '2025-10-17T18:24:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11368';
UPDATE tickets SET created_at = '2025-10-17T18:22:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11367';
UPDATE tickets SET created_at = '2025-10-17T18:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11366';
UPDATE tickets SET created_at = '2025-10-17T18:19:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11365';
UPDATE tickets SET created_at = '2025-10-17T18:17:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11364';
UPDATE tickets SET created_at = '2025-10-17T18:12:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11363';
UPDATE tickets SET created_at = '2025-10-17T18:11:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11362';
UPDATE tickets SET created_at = '2025-10-17T18:11:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11361';
UPDATE tickets SET created_at = '2025-10-17T18:08:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11360';
UPDATE tickets SET created_at = '2025-10-17T18:08:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11359';
UPDATE tickets SET created_at = '2025-10-17T18:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11358';
UPDATE tickets SET created_at = '2025-10-17T18:06:00.000Z'::timestamptz, duration_minutes = 9, objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11357';
UPDATE tickets SET created_at = '2025-10-17T17:56:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11355';
UPDATE tickets SET created_at = '2025-10-17T17:55:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11354';
UPDATE tickets SET created_at = '2025-10-17T17:55:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11353';
UPDATE tickets SET created_at = '2025-10-17T17:50:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11352';
UPDATE tickets SET created_at = '2025-10-17T17:48:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11351';
UPDATE tickets SET created_at = '2025-10-17T17:48:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11350';
UPDATE tickets SET created_at = '2025-10-17T17:48:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11349';
UPDATE tickets SET created_at = '2025-10-17T17:47:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11348';
UPDATE tickets SET created_at = '2025-10-17T17:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11347';
UPDATE tickets SET created_at = '2025-10-12T10:20:00.000Z'::timestamptz, duration_minutes = 7 WHERE jira_issue_key = 'OBCS-11297';
UPDATE tickets SET created_at = '2025-10-12T10:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11296';
UPDATE tickets SET created_at = '2025-10-12T09:53:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11295';
UPDATE tickets SET created_at = '2025-10-12T09:48:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11294';
UPDATE tickets SET created_at = '2025-10-12T09:42:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11293';
UPDATE tickets SET created_at = '2025-10-12T09:38:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11290';
UPDATE tickets SET created_at = '2025-10-12T09:36:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11289';
UPDATE tickets SET created_at = '2025-10-12T09:31:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11288';
UPDATE tickets SET created_at = '2025-10-12T09:26:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11287';
UPDATE tickets SET created_at = '2025-10-12T09:25:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11286';
UPDATE tickets SET created_at = '2025-10-12T09:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11285';
UPDATE tickets SET created_at = '2025-10-12T09:23:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11284';
UPDATE tickets SET created_at = '2025-10-12T09:21:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11283';
UPDATE tickets SET created_at = '2025-10-12T09:19:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11282';
UPDATE tickets SET created_at = '2025-10-12T09:18:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11281';
UPDATE tickets SET created_at = '2025-10-12T09:17:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11279';
UPDATE tickets SET created_at = '2025-10-12T09:16:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11278';
UPDATE tickets SET created_at = '2025-10-12T09:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11277';
UPDATE tickets SET created_at = '2025-10-12T09:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11276';
UPDATE tickets SET created_at = '2025-10-12T09:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11275';
UPDATE tickets SET created_at = '2025-10-12T09:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11274';
UPDATE tickets SET created_at = '2025-10-12T09:01:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11273';
UPDATE tickets SET created_at = '2025-10-12T08:59:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11272';
UPDATE tickets SET created_at = '2025-10-12T08:56:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11271';
UPDATE tickets SET created_at = '2025-10-11T19:16:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11269';
UPDATE tickets SET created_at = '2025-10-11T19:05:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11268';
UPDATE tickets SET created_at = '2025-10-11T19:01:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11267';
UPDATE tickets SET created_at = '2025-10-11T18:57:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11266';
UPDATE tickets SET created_at = '2025-10-11T09:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11263';
UPDATE tickets SET created_at = '2025-10-11T09:13:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11262';
UPDATE tickets SET created_at = '2025-10-10T19:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11261';
UPDATE tickets SET created_at = '2025-10-10T19:17:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11260';
UPDATE tickets SET created_at = '2025-10-10T19:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11259';
UPDATE tickets SET created_at = '2025-10-10T19:15:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11258';
UPDATE tickets SET created_at = '2025-10-10T19:15:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11257';
UPDATE tickets SET created_at = '2025-10-10T19:13:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11256';
UPDATE tickets SET created_at = '2025-10-10T19:13:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11255';
UPDATE tickets SET created_at = '2025-10-10T19:11:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11254';
UPDATE tickets SET created_at = '2025-10-10T19:11:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11253';
UPDATE tickets SET created_at = '2025-10-10T19:10:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11252';
UPDATE tickets SET created_at = '2025-10-10T19:10:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11251';
UPDATE tickets SET created_at = '2025-10-10T19:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11250';
UPDATE tickets SET created_at = '2025-10-10T19:08:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11249';
UPDATE tickets SET created_at = '2025-10-10T19:07:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11248';
UPDATE tickets SET created_at = '2025-10-10T19:07:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11247';
UPDATE tickets SET created_at = '2025-10-09T17:17:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11238';
UPDATE tickets SET created_at = '2025-10-07T18:03:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11228';
UPDATE tickets SET created_at = '2025-10-07T17:31:00.000Z'::timestamptz, duration_minutes = 18, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11227';
UPDATE tickets SET created_at = '2025-10-06T11:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11221';
UPDATE tickets SET created_at = '2025-10-06T10:33:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11220';
UPDATE tickets SET created_at = '2025-10-05T08:08:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11218';
UPDATE tickets SET created_at = '2025-10-05T08:06:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11217';
UPDATE tickets SET created_at = '2025-10-05T08:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11215';
UPDATE tickets SET created_at = '2025-10-05T07:58:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11214';
UPDATE tickets SET created_at = '2025-10-05T07:55:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11213';
UPDATE tickets SET created_at = '2025-10-05T07:53:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11212';
UPDATE tickets SET created_at = '2025-10-05T07:51:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11211';
UPDATE tickets SET created_at = '2025-10-05T07:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11210';
UPDATE tickets SET created_at = '2025-10-03T20:50:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11208';
UPDATE tickets SET created_at = '2025-10-03T20:50:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11207';
UPDATE tickets SET created_at = '2025-10-03T20:50:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11206';
UPDATE tickets SET created_at = '2025-10-03T20:49:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11205';
UPDATE tickets SET created_at = '2025-10-03T20:31:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11204';
UPDATE tickets SET created_at = '2025-10-03T20:27:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11203';
UPDATE tickets SET created_at = '2025-10-03T19:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11202';
UPDATE tickets SET created_at = '2025-10-03T19:19:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11201';
UPDATE tickets SET created_at = '2025-10-03T19:10:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11200';
UPDATE tickets SET created_at = '2025-10-03T19:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11199';
UPDATE tickets SET created_at = '2025-10-03T19:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11198';
UPDATE tickets SET created_at = '2025-10-03T19:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11197';
UPDATE tickets SET created_at = '2025-10-03T19:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11196';
UPDATE tickets SET created_at = '2025-10-03T19:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11195';
UPDATE tickets SET created_at = '2025-10-03T19:04:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11194';
UPDATE tickets SET created_at = '2025-10-03T19:01:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11193';
UPDATE tickets SET created_at = '2025-10-03T18:57:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11192';
UPDATE tickets SET created_at = '2025-10-03T18:51:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-11191';
UPDATE tickets SET created_at = '2025-10-03T18:46:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-11190';
UPDATE tickets SET created_at = '2025-10-03T18:39:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11189';
UPDATE tickets SET created_at = '2025-10-03T18:11:00.000Z'::timestamptz, duration_minutes = 20, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11188';
UPDATE tickets SET created_at = '2025-10-03T16:39:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11177';
UPDATE tickets SET created_at = '2025-10-03T16:22:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11174';
UPDATE tickets SET created_at = '2025-10-03T16:19:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11173';
UPDATE tickets SET created_at = '2025-10-03T16:18:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11172';
UPDATE tickets SET created_at = '2025-10-03T16:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11171';
UPDATE tickets SET created_at = '2025-10-03T16:16:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11170';
UPDATE tickets SET created_at = '2025-10-03T16:15:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11169';
UPDATE tickets SET created_at = '2025-10-03T16:15:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11168';
UPDATE tickets SET created_at = '2025-10-03T16:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11167';
UPDATE tickets SET created_at = '2025-10-03T16:13:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11166';
UPDATE tickets SET created_at = '2025-10-03T16:12:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11165';
UPDATE tickets SET created_at = '2025-10-03T16:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11164';
UPDATE tickets SET created_at = '2025-10-03T16:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11163';
UPDATE tickets SET created_at = '2025-10-03T16:11:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11162';
UPDATE tickets SET created_at = '2025-10-03T16:11:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11161';
UPDATE tickets SET created_at = '2025-10-03T16:11:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11160';
UPDATE tickets SET created_at = '2025-10-03T15:58:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11159';
UPDATE tickets SET created_at = '2025-10-03T15:57:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11158';
UPDATE tickets SET created_at = '2025-10-03T15:56:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11157';
UPDATE tickets SET created_at = '2025-10-03T15:55:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11156';
UPDATE tickets SET created_at = '2025-10-03T15:54:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11155';
UPDATE tickets SET created_at = '2025-10-03T15:54:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11154';
UPDATE tickets SET created_at = '2025-10-03T15:52:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11153';
UPDATE tickets SET created_at = '2025-10-03T15:52:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11152';
UPDATE tickets SET created_at = '2025-10-03T15:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11151';
UPDATE tickets SET created_at = '2025-09-28T19:28:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11143';
UPDATE tickets SET created_at = '2025-09-28T19:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11142';
UPDATE tickets SET created_at = '2025-09-28T19:21:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11141';
UPDATE tickets SET created_at = '2025-09-28T19:19:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11140';
UPDATE tickets SET created_at = '2025-09-28T19:11:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11138';
UPDATE tickets SET created_at = '2025-09-28T19:06:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11137';
UPDATE tickets SET created_at = '2025-09-28T19:02:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11136';
UPDATE tickets SET created_at = '2025-09-28T18:58:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11135';
UPDATE tickets SET created_at = '2025-09-28T18:54:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11134';
UPDATE tickets SET created_at = '2025-09-28T18:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11133';
UPDATE tickets SET created_at = '2025-09-28T17:03:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11132';
UPDATE tickets SET created_at = '2025-09-28T15:41:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11131';
UPDATE tickets SET created_at = '2025-09-28T15:32:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11130';
UPDATE tickets SET created_at = '2025-09-28T15:31:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11129';
UPDATE tickets SET created_at = '2025-09-28T15:31:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11128';
UPDATE tickets SET created_at = '2025-09-28T15:30:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11127';
UPDATE tickets SET created_at = '2025-09-28T15:30:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11126';
UPDATE tickets SET created_at = '2025-09-28T15:28:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11125';
UPDATE tickets SET created_at = '2025-09-28T15:27:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11124';
UPDATE tickets SET created_at = '2025-09-28T15:27:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11123';
UPDATE tickets SET created_at = '2025-09-28T15:24:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11122';
UPDATE tickets SET created_at = '2025-09-28T09:34:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11121';
UPDATE tickets SET created_at = '2025-09-28T09:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11120';
UPDATE tickets SET created_at = '2025-09-28T09:25:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11119';
UPDATE tickets SET created_at = '2025-09-28T09:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11118';
UPDATE tickets SET created_at = '2025-09-28T09:16:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11117';
UPDATE tickets SET created_at = '2025-09-28T09:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11116';
UPDATE tickets SET created_at = '2025-09-28T09:11:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11115';
UPDATE tickets SET created_at = '2025-09-28T09:10:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11114';
UPDATE tickets SET created_at = '2025-09-28T09:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11113';
UPDATE tickets SET created_at = '2025-09-28T09:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11112';
UPDATE tickets SET created_at = '2025-09-28T09:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11111';
UPDATE tickets SET created_at = '2025-09-27T14:04:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11110';
UPDATE tickets SET created_at = '2025-09-26T11:19:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11098';
UPDATE tickets SET created_at = '2025-09-26T11:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11097';
UPDATE tickets SET created_at = '2025-09-26T11:13:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11096';
UPDATE tickets SET created_at = '2025-09-26T11:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11095';
UPDATE tickets SET created_at = '2025-09-26T11:11:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11094';
UPDATE tickets SET created_at = '2025-09-26T11:00:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11093';
UPDATE tickets SET created_at = '2025-09-26T10:59:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11092';
UPDATE tickets SET created_at = '2025-09-26T10:58:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11091';
UPDATE tickets SET created_at = '2025-09-22T07:39:00.000Z'::timestamptz, duration_minutes = 16, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11085';
UPDATE tickets SET created_at = '2025-09-22T06:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11080';
UPDATE tickets SET created_at = '2025-09-21T20:49:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11079';
UPDATE tickets SET created_at = '2025-09-21T20:47:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11078';
UPDATE tickets SET created_at = '2025-09-21T20:46:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11077';
UPDATE tickets SET created_at = '2025-09-21T20:46:00.000Z'::timestamptz, duration_minutes = 18, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11076';
UPDATE tickets SET created_at = '2025-09-21T20:46:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11075';
UPDATE tickets SET created_at = '2025-09-21T20:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11074';
UPDATE tickets SET created_at = '2025-09-21T20:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-11073';
UPDATE tickets SET created_at = '2025-09-21T20:40:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11072';
UPDATE tickets SET created_at = '2025-09-21T20:39:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11071';
UPDATE tickets SET created_at = '2025-09-21T20:38:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11070';
UPDATE tickets SET created_at = '2025-09-21T20:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-11069';
UPDATE tickets SET created_at = '2025-09-21T20:32:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11068';
UPDATE tickets SET created_at = '2025-09-21T20:30:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11067';
UPDATE tickets SET created_at = '2025-09-21T20:28:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11066';
UPDATE tickets SET created_at = '2025-09-21T20:28:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11065';
UPDATE tickets SET created_at = '2025-09-21T20:27:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11064';
UPDATE tickets SET created_at = '2025-09-21T20:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11063';
UPDATE tickets SET created_at = '2025-09-21T20:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11062';
UPDATE tickets SET created_at = '2025-09-21T20:23:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11061';
UPDATE tickets SET created_at = '2025-09-21T20:22:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11060';
UPDATE tickets SET created_at = '2025-09-21T20:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11059';
UPDATE tickets SET created_at = '2025-09-21T20:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11058';
UPDATE tickets SET created_at = '2025-09-21T20:16:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11057';
UPDATE tickets SET created_at = '2025-09-21T20:05:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11056';
UPDATE tickets SET created_at = '2025-09-21T20:00:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11055';
UPDATE tickets SET created_at = '2025-09-21T19:59:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11054';
UPDATE tickets SET created_at = '2025-09-21T19:58:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11053';
UPDATE tickets SET created_at = '2025-09-21T19:57:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11052';
UPDATE tickets SET created_at = '2025-09-21T19:57:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11051';
UPDATE tickets SET created_at = '2025-09-21T19:56:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11050';
UPDATE tickets SET created_at = '2025-09-21T19:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11049';
UPDATE tickets SET created_at = '2025-09-21T19:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11048';
UPDATE tickets SET created_at = '2025-09-21T19:52:00.000Z'::timestamptz, duration_minutes = 17, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11047';
UPDATE tickets SET created_at = '2025-09-21T19:52:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11046';
UPDATE tickets SET created_at = '2025-09-21T19:49:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11045';
UPDATE tickets SET created_at = '2025-09-21T19:48:00.000Z'::timestamptz, duration_minutes = 22, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11044';
UPDATE tickets SET created_at = '2025-09-21T19:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11043';
UPDATE tickets SET created_at = '2025-09-21T19:44:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11042';
UPDATE tickets SET created_at = '2025-09-21T19:43:00.000Z'::timestamptz, duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11041';
UPDATE tickets SET created_at = '2025-09-21T19:42:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11040';
UPDATE tickets SET created_at = '2025-09-21T19:41:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11039';
UPDATE tickets SET created_at = '2025-09-21T19:40:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11038';
UPDATE tickets SET created_at = '2025-09-21T19:40:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11037';
UPDATE tickets SET created_at = '2025-09-21T19:39:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11036';
UPDATE tickets SET created_at = '2025-09-21T19:38:00.000Z'::timestamptz, duration_minutes = 16, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11035';
UPDATE tickets SET created_at = '2025-09-21T19:37:00.000Z'::timestamptz, duration_minutes = 20, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11034';
UPDATE tickets SET created_at = '2025-09-21T19:36:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11033';
UPDATE tickets SET created_at = '2025-09-21T19:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11032';
UPDATE tickets SET created_at = '2025-09-21T19:34:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11031';
UPDATE tickets SET created_at = '2025-09-21T19:34:00.000Z'::timestamptz, duration_minutes = 39, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11030';
UPDATE tickets SET created_at = '2025-09-21T19:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11029';
UPDATE tickets SET created_at = '2025-09-21T19:32:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11028';
UPDATE tickets SET created_at = '2025-09-21T19:31:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11027';
UPDATE tickets SET created_at = '2025-09-21T19:31:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11026';
UPDATE tickets SET created_at = '2025-09-21T19:31:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11025';
UPDATE tickets SET created_at = '2025-09-21T19:30:00.000Z'::timestamptz, duration_minutes = 38, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11024';
UPDATE tickets SET created_at = '2025-09-21T19:30:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11023';
UPDATE tickets SET created_at = '2025-09-21T19:30:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11022';
UPDATE tickets SET created_at = '2025-09-21T19:29:00.000Z'::timestamptz, duration_minutes = 32, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11021';
UPDATE tickets SET created_at = '2025-09-21T19:29:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11020';
UPDATE tickets SET created_at = '2025-09-21T19:29:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11019';
UPDATE tickets SET created_at = '2025-09-21T19:29:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11018';
UPDATE tickets SET created_at = '2025-09-21T19:28:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11017';
UPDATE tickets SET created_at = '2025-09-21T19:28:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11016';
UPDATE tickets SET created_at = '2025-09-21T19:28:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11015';
UPDATE tickets SET created_at = '2025-09-21T19:27:00.000Z'::timestamptz, duration_minutes = 28, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11014';
UPDATE tickets SET created_at = '2025-09-21T19:27:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11013';
UPDATE tickets SET created_at = '2025-09-21T19:26:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11012';
UPDATE tickets SET created_at = '2025-09-20T21:32:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11010';
UPDATE tickets SET created_at = '2025-09-20T21:12:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11009';
UPDATE tickets SET created_at = '2025-09-20T21:01:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-11008';
UPDATE tickets SET created_at = '2025-09-20T20:56:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11007';
UPDATE tickets SET created_at = '2025-09-20T20:47:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-11006';
UPDATE tickets SET created_at = '2025-09-20T20:40:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11005';
UPDATE tickets SET created_at = '2025-09-20T20:20:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11004';
UPDATE tickets SET created_at = '2025-09-20T20:15:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11003';
UPDATE tickets SET created_at = '2025-09-20T20:04:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-11002';
UPDATE tickets SET created_at = '2025-09-19T18:27:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10990';
UPDATE tickets SET created_at = '2025-09-19T18:26:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10989';
UPDATE tickets SET created_at = '2025-09-19T18:23:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10988';
UPDATE tickets SET created_at = '2025-09-19T18:16:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10987';
UPDATE tickets SET created_at = '2025-09-19T18:09:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10986';
UPDATE tickets SET created_at = '2025-09-19T18:01:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10985';
UPDATE tickets SET created_at = '2025-09-19T17:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10984';
UPDATE tickets SET created_at = '2025-09-19T17:49:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10983';
UPDATE tickets SET created_at = '2025-09-19T17:44:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10982';
UPDATE tickets SET created_at = '2025-09-19T17:43:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10981';
UPDATE tickets SET created_at = '2025-09-19T17:42:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10980';
UPDATE tickets SET created_at = '2025-09-19T17:41:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10979';
UPDATE tickets SET created_at = '2025-09-19T17:39:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10978';
UPDATE tickets SET created_at = '2025-09-19T17:28:00.000Z'::timestamptz, duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10977';
UPDATE tickets SET created_at = '2025-09-19T17:25:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10976';
UPDATE tickets SET created_at = '2025-09-19T17:18:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10975';
UPDATE tickets SET created_at = '2025-09-19T16:56:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10974';
UPDATE tickets SET created_at = '2025-09-19T16:56:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10973';
UPDATE tickets SET created_at = '2025-09-19T16:55:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10972';
UPDATE tickets SET created_at = '2025-09-19T16:51:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10971';
UPDATE tickets SET created_at = '2025-09-19T16:51:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10970';
UPDATE tickets SET created_at = '2025-09-19T16:50:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10969';
UPDATE tickets SET created_at = '2025-09-19T16:50:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10968';
UPDATE tickets SET created_at = '2025-09-14T13:36:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10946';
UPDATE tickets SET created_at = '2025-09-14T13:32:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10945';
UPDATE tickets SET created_at = '2025-09-14T13:31:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10944';
UPDATE tickets SET created_at = '2025-09-14T13:28:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10943';
UPDATE tickets SET created_at = '2025-09-14T13:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10942';
UPDATE tickets SET created_at = '2025-09-14T13:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10941';
UPDATE tickets SET created_at = '2025-09-14T13:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10940';
UPDATE tickets SET created_at = '2025-09-14T13:13:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10939';
UPDATE tickets SET created_at = '2025-09-14T12:44:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10938';
UPDATE tickets SET created_at = '2025-09-14T12:40:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10937';
UPDATE tickets SET created_at = '2025-09-14T12:31:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10936';
UPDATE tickets SET created_at = '2025-09-14T12:28:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10935';
UPDATE tickets SET created_at = '2025-09-14T12:26:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10934';
UPDATE tickets SET created_at = '2025-09-14T12:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Requête' WHERE jira_issue_key = 'OBCS-10933';
UPDATE tickets SET created_at = '2025-09-14T12:23:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10932';
UPDATE tickets SET created_at = '2025-09-14T12:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10929';
UPDATE tickets SET created_at = '2025-09-14T12:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10928';
UPDATE tickets SET created_at = '2025-09-14T12:10:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10927';
UPDATE tickets SET created_at = '2025-09-14T12:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10926';
UPDATE tickets SET created_at = '2025-09-14T12:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10925';
UPDATE tickets SET created_at = '2025-09-14T12:02:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10924';
UPDATE tickets SET created_at = '2025-09-14T11:58:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10923';
UPDATE tickets SET created_at = '2025-09-14T11:55:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10922';
UPDATE tickets SET created_at = '2025-09-14T11:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10921';
UPDATE tickets SET created_at = '2025-09-14T11:48:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10920';
UPDATE tickets SET created_at = '2025-09-14T11:43:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10919';
UPDATE tickets SET created_at = '2025-09-12T20:32:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10907';
UPDATE tickets SET created_at = '2025-09-12T20:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10906';
UPDATE tickets SET created_at = '2025-09-12T20:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10905';
UPDATE tickets SET created_at = '2025-09-12T20:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10904';
UPDATE tickets SET created_at = '2025-09-12T20:24:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10903';
UPDATE tickets SET created_at = '2025-09-12T20:22:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10902';
UPDATE tickets SET created_at = '2025-09-12T20:13:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10901';
UPDATE tickets SET created_at = '2025-09-12T20:12:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10900';
UPDATE tickets SET created_at = '2025-09-12T20:11:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10899';
UPDATE tickets SET created_at = '2025-09-12T20:11:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10898';
UPDATE tickets SET created_at = '2025-09-12T20:06:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10897';
UPDATE tickets SET created_at = '2025-09-12T20:06:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10896';
UPDATE tickets SET created_at = '2025-09-12T20:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10895';
UPDATE tickets SET created_at = '2025-09-12T20:04:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10894';
UPDATE tickets SET created_at = '2025-09-12T20:00:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10893';
UPDATE tickets SET created_at = '2025-09-12T19:59:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10892';
UPDATE tickets SET created_at = '2025-09-12T19:58:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10891';
UPDATE tickets SET created_at = '2025-09-12T19:57:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10890';
UPDATE tickets SET created_at = '2025-09-12T19:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10889';
UPDATE tickets SET created_at = '2025-09-12T19:54:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10888';
UPDATE tickets SET created_at = '2025-09-12T19:52:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10887';
UPDATE tickets SET created_at = '2025-09-12T19:51:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10886';
UPDATE tickets SET created_at = '2025-09-12T18:16:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Bug' WHERE jira_issue_key = 'OBCS-10884';
UPDATE tickets SET created_at = '2025-09-12T18:00:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10883';
UPDATE tickets SET created_at = '2025-09-12T17:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10882';
UPDATE tickets SET created_at = '2025-09-12T17:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Pr��cisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10881';
UPDATE tickets SET created_at = '2025-09-08T16:56:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10869';
UPDATE tickets SET created_at = '2025-09-07T22:18:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10865';
UPDATE tickets SET created_at = '2025-09-07T22:18:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10864';
UPDATE tickets SET created_at = '2025-09-07T22:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10863';
UPDATE tickets SET created_at = '2025-09-07T22:16:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10862';
UPDATE tickets SET created_at = '2025-09-07T22:16:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10861';
UPDATE tickets SET created_at = '2025-09-07T22:14:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne' WHERE jira_issue_key = 'OBCS-10860';
UPDATE tickets SET created_at = '2025-09-07T22:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne' WHERE jira_issue_key = 'OBCS-10859';
UPDATE tickets SET created_at = '2025-09-07T21:51:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne' WHERE jira_issue_key = 'OBCS-10858';
UPDATE tickets SET created_at = '2025-09-07T21:50:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne' WHERE jira_issue_key = 'OBCS-10857';
UPDATE tickets SET created_at = '2025-09-07T21:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne' WHERE jira_issue_key = 'OBCS-10856';
UPDATE tickets SET created_at = '2025-09-07T21:45:00.000Z'::timestamptz, action_menee = 'Explication en ligne' WHERE jira_issue_key = 'OBCS-10855';
UPDATE tickets SET created_at = '2025-09-07T21:36:00.000Z'::timestamptz WHERE jira_issue_key = 'OBCS-10854';
UPDATE tickets SET created_at = '2025-09-07T21:26:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10853';
UPDATE tickets SET created_at = '2025-09-07T21:22:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10852';
UPDATE tickets SET created_at = '2025-09-07T21:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10851';
UPDATE tickets SET created_at = '2025-09-07T21:15:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10850';
UPDATE tickets SET created_at = '2025-09-07T21:11:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10849';
UPDATE tickets SET created_at = '2025-09-07T21:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10848';
UPDATE tickets SET created_at = '2025-09-07T17:11:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10847';
UPDATE tickets SET created_at = '2025-09-07T17:10:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10846';
UPDATE tickets SET created_at = '2025-09-07T17:06:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10845';
UPDATE tickets SET created_at = '2025-09-07T17:05:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10844';
UPDATE tickets SET created_at = '2025-09-07T17:03:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10843';
UPDATE tickets SET created_at = '2025-09-07T17:03:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10842';
UPDATE tickets SET created_at = '2025-09-07T17:02:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10841';
UPDATE tickets SET created_at = '2025-09-07T17:02:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10840';
UPDATE tickets SET created_at = '2025-09-07T16:55:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10839';
UPDATE tickets SET created_at = '2025-09-07T16:53:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10838';
UPDATE tickets SET created_at = '2025-09-07T16:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10837';
UPDATE tickets SET created_at = '2025-09-07T16:48:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10836';
UPDATE tickets SET created_at = '2025-09-07T16:46:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10835';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10791';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10790';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10789';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10788';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10787';
UPDATE tickets SET duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10786';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10785';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10784';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10783';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10782';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10781';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10780';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10779';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10778';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10777';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10776';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10775';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10774';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10773';
UPDATE tickets SET duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10772';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Mailing', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10771';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Mailing', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10770';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10769';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10768';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10767';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10766';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-10765';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10764';
UPDATE tickets SET duration_minutes = 28 WHERE jira_issue_key = 'OBCS-10763';
UPDATE tickets SET duration_minutes = 13, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10762';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-10761';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10760';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10754';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10753';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10751';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10750';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10745';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10743';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-10742';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10741';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10740';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10739';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10738';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10734';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10733';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10732';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10731';
UPDATE tickets SET duration_minutes = 0 WHERE jira_issue_key = 'OBCS-10730';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10729';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10728';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10727';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10724';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10723';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10722';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10721';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10720';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Mailing', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10719';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10718';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10717';
UPDATE tickets SET duration_minutes = 9 WHERE jira_issue_key = 'OBCS-10716';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10715';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10714';
UPDATE tickets SET duration_minutes = 45, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10713';
UPDATE tickets SET duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10712';
UPDATE tickets SET duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10711';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10710';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10709';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-10699';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10698';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10697';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10670';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10669';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10668';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10667';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10666';
UPDATE tickets SET duration_minutes = 10 WHERE jira_issue_key = 'OBCS-10665';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10664';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10663';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10661';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10660';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10659';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10658';
UPDATE tickets SET duration_minutes = 26 WHERE jira_issue_key = 'OBCS-10657';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10656';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10655';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10654';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10653';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10652';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10651';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10650';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10649';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10648';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10647';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10646';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10645';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10644';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10643';
UPDATE tickets SET duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10642';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10641';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10640';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10639';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10638';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-10621';
UPDATE tickets SET duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10620';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10619';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10618';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10616';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10615';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10614';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-10613';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10612';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10611';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10610';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10609';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10608';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10607';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10606';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10605';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10604';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10603';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10602';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10593';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10592';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10591';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10590';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10589';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10588';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10587';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10586';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-10585';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10584';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10583';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10582';
UPDATE tickets SET duration_minutes = 14, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10581';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10580';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10579';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10578';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-10577';
