-- OnpointDoc - Mise à jour des tickets d'assistance depuis l'export JIRA (PARTIE 7)
-- Date: 2025-12-10
-- Description: Met à jour created_at, duration_minutes, action_menee et objet_principal
-- Partie 7 sur 15 (500 tickets)

UPDATE tickets SET created_at = '2024-10-12T21:38:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7202';
UPDATE tickets SET created_at = '2024-10-12T21:38:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7201';
UPDATE tickets SET created_at = '2024-10-12T21:29:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7200';
UPDATE tickets SET created_at = '2024-10-12T21:29:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7199';
UPDATE tickets SET created_at = '2024-10-12T21:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7198';
UPDATE tickets SET created_at = '2024-10-12T21:19:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7197';
UPDATE tickets SET created_at = '2024-10-12T21:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7196';
UPDATE tickets SET created_at = '2024-10-12T21:17:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7195';
UPDATE tickets SET created_at = '2024-10-12T21:17:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7194';
UPDATE tickets SET created_at = '2024-10-12T21:17:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7193';
UPDATE tickets SET created_at = '2024-10-12T21:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7192';
UPDATE tickets SET created_at = '2024-10-12T21:15:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7191';
UPDATE tickets SET created_at = '2024-10-12T21:14:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7190';
UPDATE tickets SET created_at = '2024-10-12T21:12:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7189';
UPDATE tickets SET created_at = '2024-10-12T10:47:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7182';
UPDATE tickets SET created_at = '2024-10-12T10:45:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7181';
UPDATE tickets SET created_at = '2024-10-12T10:43:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-7180';
UPDATE tickets SET created_at = '2024-10-12T10:40:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7179';
UPDATE tickets SET created_at = '2024-10-12T10:39:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7178';
UPDATE tickets SET created_at = '2024-10-12T10:38:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7177';
UPDATE tickets SET created_at = '2024-10-12T10:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7176';
UPDATE tickets SET created_at = '2024-10-12T10:35:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7175';
UPDATE tickets SET created_at = '2024-10-12T10:33:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7174';
UPDATE tickets SET created_at = '2024-10-12T10:30:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7173';
UPDATE tickets SET created_at = '2024-10-12T10:29:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7172';
UPDATE tickets SET created_at = '2024-10-12T10:28:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7171';
UPDATE tickets SET created_at = '2024-10-12T10:24:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7170';
UPDATE tickets SET created_at = '2024-10-12T10:22:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7169';
UPDATE tickets SET created_at = '2024-10-12T10:20:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7168';
UPDATE tickets SET created_at = '2024-10-12T10:19:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7167';
UPDATE tickets SET created_at = '2024-10-12T10:17:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7166';
UPDATE tickets SET created_at = '2024-10-12T10:16:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7165';
UPDATE tickets SET created_at = '2024-10-12T10:15:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7164';
UPDATE tickets SET created_at = '2024-10-12T10:13:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7163';
UPDATE tickets SET created_at = '2024-10-12T10:12:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7162';
UPDATE tickets SET created_at = '2024-10-07T18:49:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7145';
UPDATE tickets SET created_at = '2024-10-06T20:54:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7133';
UPDATE tickets SET created_at = '2024-10-06T20:54:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7132';
UPDATE tickets SET created_at = '2024-10-06T20:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7131';
UPDATE tickets SET created_at = '2024-10-06T20:50:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7130';
UPDATE tickets SET created_at = '2024-10-06T20:48:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7129';
UPDATE tickets SET created_at = '2024-10-06T20:46:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7128';
UPDATE tickets SET created_at = '2024-10-06T20:46:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7127';
UPDATE tickets SET created_at = '2024-10-06T20:43:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7126';
UPDATE tickets SET created_at = '2024-10-06T20:41:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7125';
UPDATE tickets SET created_at = '2024-10-06T20:40:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7124';
UPDATE tickets SET created_at = '2024-10-06T20:39:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7123';
UPDATE tickets SET created_at = '2024-10-06T09:24:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7121';
UPDATE tickets SET created_at = '2024-10-06T09:22:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7120';
UPDATE tickets SET created_at = '2024-10-06T09:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Mailing', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7119';
UPDATE tickets SET created_at = '2024-10-04T20:51:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7113';
UPDATE tickets SET created_at = '2024-10-04T20:50:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7112';
UPDATE tickets SET created_at = '2024-10-04T20:49:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7111';
UPDATE tickets SET created_at = '2024-10-04T20:41:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7110';
UPDATE tickets SET created_at = '2024-10-04T20:39:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7109';
UPDATE tickets SET created_at = '2024-10-04T20:38:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7108';
UPDATE tickets SET created_at = '2024-10-04T20:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7107';
UPDATE tickets SET created_at = '2024-10-04T20:34:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7106';
UPDATE tickets SET created_at = '2024-10-04T20:10:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7105';
UPDATE tickets SET created_at = '2024-10-04T20:06:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7104';
UPDATE tickets SET created_at = '2024-10-04T20:04:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7103';
UPDATE tickets SET created_at = '2024-10-04T19:58:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7102';
UPDATE tickets SET created_at = '2024-10-04T19:56:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7101';
UPDATE tickets SET created_at = '2024-10-04T19:53:00.000Z'::timestamptz, duration_minutes = 70, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7100';
UPDATE tickets SET created_at = '2024-10-04T19:51:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7099';
UPDATE tickets SET created_at = '2024-10-04T19:47:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7098';
UPDATE tickets SET created_at = '2024-10-04T19:45:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7097';
UPDATE tickets SET created_at = '2024-10-04T19:39:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7096';
UPDATE tickets SET created_at = '2024-10-04T19:35:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7095';
UPDATE tickets SET created_at = '2024-10-04T10:56:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7075';
UPDATE tickets SET created_at = '2024-10-04T10:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7074';
UPDATE tickets SET created_at = '2024-10-04T10:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7073';
UPDATE tickets SET created_at = '2024-10-04T10:54:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7072';
UPDATE tickets SET created_at = '2024-10-04T10:53:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7071';
UPDATE tickets SET created_at = '2024-10-04T10:47:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7070';
UPDATE tickets SET created_at = '2024-10-04T10:44:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7069';
UPDATE tickets SET created_at = '2024-10-04T10:44:00.000Z'::timestamptz, duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7068';
UPDATE tickets SET created_at = '2024-10-04T10:44:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7067';
UPDATE tickets SET created_at = '2024-10-04T10:43:00.000Z'::timestamptz, duration_minutes = 47, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7066';
UPDATE tickets SET created_at = '2024-10-04T10:41:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7065';
UPDATE tickets SET created_at = '2024-10-04T10:21:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7064';
UPDATE tickets SET created_at = '2024-10-04T10:17:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7063';
UPDATE tickets SET created_at = '2024-10-04T10:17:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7062';
UPDATE tickets SET created_at = '2024-10-04T10:16:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7061';
UPDATE tickets SET created_at = '2024-10-03T16:20:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7058';
UPDATE tickets SET created_at = '2024-10-02T20:34:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7055';
UPDATE tickets SET created_at = '2024-10-02T20:31:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7054';
UPDATE tickets SET created_at = '2024-10-02T20:29:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7053';
UPDATE tickets SET created_at = '2024-10-02T20:26:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7052';
UPDATE tickets SET created_at = '2024-09-29T17:29:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7036';
UPDATE tickets SET created_at = '2024-09-29T17:27:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7035';
UPDATE tickets SET created_at = '2024-09-29T17:18:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7034';
UPDATE tickets SET created_at = '2024-09-29T16:24:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7031';
UPDATE tickets SET created_at = '2024-09-29T16:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7030';
UPDATE tickets SET created_at = '2024-09-29T16:16:00.000Z'::timestamptz, duration_minutes = 51, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7029';
UPDATE tickets SET created_at = '2024-09-29T16:12:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7028';
UPDATE tickets SET created_at = '2024-09-29T15:00:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7027';
UPDATE tickets SET created_at = '2024-09-29T14:59:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7026';
UPDATE tickets SET created_at = '2024-09-29T14:59:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7025';
UPDATE tickets SET created_at = '2024-09-29T14:58:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7024';
UPDATE tickets SET created_at = '2024-09-29T14:57:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7023';
UPDATE tickets SET created_at = '2024-09-29T14:56:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7022';
UPDATE tickets SET created_at = '2024-09-29T14:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7021';
UPDATE tickets SET created_at = '2024-09-29T14:55:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7020';
UPDATE tickets SET created_at = '2024-09-29T14:55:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7019';
UPDATE tickets SET created_at = '2024-09-29T14:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7018';
UPDATE tickets SET created_at = '2024-09-29T14:54:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7017';
UPDATE tickets SET created_at = '2024-09-29T14:54:00.000Z'::timestamptz, duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7016';
UPDATE tickets SET created_at = '2024-09-29T14:54:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7015';
UPDATE tickets SET created_at = '2024-09-29T14:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7014';
UPDATE tickets SET created_at = '2024-09-29T14:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-7013';
UPDATE tickets SET created_at = '2024-09-29T14:51:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7012';
UPDATE tickets SET created_at = '2024-09-29T14:50:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-7011';
UPDATE tickets SET created_at = '2024-09-29T09:52:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7008';
UPDATE tickets SET created_at = '2024-09-29T09:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7007';
UPDATE tickets SET created_at = '2024-09-29T09:50:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-7006';
UPDATE tickets SET created_at = '2024-09-29T09:48:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-7005';
UPDATE tickets SET created_at = '2024-09-28T12:28:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6998';
UPDATE tickets SET created_at = '2024-09-28T12:24:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6997';
UPDATE tickets SET created_at = '2024-09-28T12:21:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6996';
UPDATE tickets SET created_at = '2024-09-28T12:20:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6995';
UPDATE tickets SET created_at = '2024-09-28T12:15:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6994';
UPDATE tickets SET created_at = '2024-09-28T12:08:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6993';
UPDATE tickets SET created_at = '2024-09-28T12:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6992';
UPDATE tickets SET created_at = '2024-09-28T12:03:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6991';
UPDATE tickets SET created_at = '2024-09-28T12:00:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6990';
UPDATE tickets SET created_at = '2024-09-27T20:00:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6988';
UPDATE tickets SET created_at = '2024-09-27T20:00:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6987';
UPDATE tickets SET created_at = '2024-09-27T19:59:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6986';
UPDATE tickets SET created_at = '2024-09-27T19:59:00.000Z'::timestamptz, duration_minutes = 27, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6985';
UPDATE tickets SET created_at = '2024-09-27T19:57:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6984';
UPDATE tickets SET created_at = '2024-09-27T19:57:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6983';
UPDATE tickets SET created_at = '2024-09-27T19:55:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6982';
UPDATE tickets SET created_at = '2024-09-27T19:54:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6981';
UPDATE tickets SET created_at = '2024-09-27T19:53:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6980';
UPDATE tickets SET created_at = '2024-09-27T19:51:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6979';
UPDATE tickets SET created_at = '2024-09-27T19:51:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6978';
UPDATE tickets SET created_at = '2024-09-27T19:51:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6977';
UPDATE tickets SET created_at = '2024-09-27T19:50:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6976';
UPDATE tickets SET created_at = '2024-09-27T19:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6975';
UPDATE tickets SET created_at = '2024-09-27T19:49:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6974';
UPDATE tickets SET created_at = '2024-09-22T14:50:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6929';
UPDATE tickets SET created_at = '2024-09-21T18:59:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6920';
UPDATE tickets SET created_at = '2024-09-21T18:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6919';
UPDATE tickets SET created_at = '2024-09-21T18:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6918';
UPDATE tickets SET created_at = '2024-09-21T18:50:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6917';
UPDATE tickets SET created_at = '2024-09-21T11:37:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6911';
UPDATE tickets SET created_at = '2024-09-21T11:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6910';
UPDATE tickets SET created_at = '2024-09-21T11:34:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6909';
UPDATE tickets SET created_at = '2024-09-21T11:33:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6908';
UPDATE tickets SET created_at = '2024-09-21T11:32:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6907';
UPDATE tickets SET created_at = '2024-09-21T11:30:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6906';
UPDATE tickets SET created_at = '2024-09-21T11:27:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6905';
UPDATE tickets SET created_at = '2024-09-21T11:25:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6904';
UPDATE tickets SET created_at = '2024-09-21T11:24:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6903';
UPDATE tickets SET created_at = '2024-09-21T11:22:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6902';
UPDATE tickets SET created_at = '2024-09-20T20:04:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6898';
UPDATE tickets SET created_at = '2024-09-20T19:57:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6897';
UPDATE tickets SET created_at = '2024-09-20T19:55:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6896';
UPDATE tickets SET created_at = '2024-09-20T18:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6891';
UPDATE tickets SET created_at = '2024-09-20T18:47:00.000Z'::timestamptz, duration_minutes = 41, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6890';
UPDATE tickets SET created_at = '2024-09-20T18:46:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6889';
UPDATE tickets SET created_at = '2024-09-20T18:46:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6888';
UPDATE tickets SET created_at = '2024-09-20T18:45:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6887';
UPDATE tickets SET created_at = '2024-09-20T18:45:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6886';
UPDATE tickets SET created_at = '2024-09-20T18:44:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6885';
UPDATE tickets SET created_at = '2024-09-20T18:44:00.000Z'::timestamptz, duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6884';
UPDATE tickets SET created_at = '2024-09-20T18:42:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6883';
UPDATE tickets SET created_at = '2024-09-20T18:42:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6882';
UPDATE tickets SET created_at = '2024-09-20T18:41:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6881';
UPDATE tickets SET created_at = '2024-09-20T18:41:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6880';
UPDATE tickets SET created_at = '2024-09-20T18:40:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6879';
UPDATE tickets SET created_at = '2024-09-20T18:39:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6878';
UPDATE tickets SET created_at = '2024-09-20T18:39:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6877';
UPDATE tickets SET created_at = '2024-09-20T18:39:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6876';
UPDATE tickets SET created_at = '2024-09-20T18:38:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6875';
UPDATE tickets SET created_at = '2024-09-20T18:38:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6874';
UPDATE tickets SET created_at = '2024-09-19T11:04:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6865';
UPDATE tickets SET created_at = '2024-09-17T19:00:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6856';
UPDATE tickets SET created_at = '2024-09-17T18:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6855';
UPDATE tickets SET created_at = '2024-09-17T18:51:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6854';
UPDATE tickets SET created_at = '2024-09-17T18:49:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6853';
UPDATE tickets SET created_at = '2024-09-17T18:41:00.000Z'::timestamptz, duration_minutes = 15 WHERE jira_issue_key = 'OBCS-6852';
UPDATE tickets SET created_at = '2024-09-14T12:29:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6834';
UPDATE tickets SET created_at = '2024-09-14T12:25:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6833';
UPDATE tickets SET created_at = '2024-09-14T12:12:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6832';
UPDATE tickets SET created_at = '2024-09-14T12:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6831';
UPDATE tickets SET created_at = '2024-09-14T12:08:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6830';
UPDATE tickets SET created_at = '2024-09-14T12:07:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6829';
UPDATE tickets SET created_at = '2024-09-14T12:05:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6828';
UPDATE tickets SET created_at = '2024-09-13T19:45:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6825';
UPDATE tickets SET created_at = '2024-09-13T19:43:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6824';
UPDATE tickets SET created_at = '2024-09-13T19:42:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6823';
UPDATE tickets SET created_at = '2024-09-13T19:41:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6822';
UPDATE tickets SET created_at = '2024-09-13T19:33:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6819';
UPDATE tickets SET created_at = '2024-09-13T19:33:00.000Z'::timestamptz, duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6818';
UPDATE tickets SET created_at = '2024-09-13T19:31:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6816';
UPDATE tickets SET created_at = '2024-09-13T19:30:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6815';
UPDATE tickets SET created_at = '2024-09-13T19:29:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6813';
UPDATE tickets SET created_at = '2024-09-13T19:28:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6811';
UPDATE tickets SET created_at = '2024-09-13T19:28:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6810';
UPDATE tickets SET created_at = '2024-09-13T19:27:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6809';
UPDATE tickets SET created_at = '2024-09-13T19:27:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6808';
UPDATE tickets SET created_at = '2024-09-13T19:26:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6807';
UPDATE tickets SET created_at = '2024-09-13T19:25:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6805';
UPDATE tickets SET created_at = '2024-09-13T19:25:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6804';
UPDATE tickets SET created_at = '2024-09-13T19:24:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6802';
UPDATE tickets SET created_at = '2024-09-13T19:23:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6801';
UPDATE tickets SET created_at = '2024-09-13T19:21:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6800';
UPDATE tickets SET created_at = '2024-09-13T19:21:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6799';
UPDATE tickets SET created_at = '2024-09-13T19:14:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6798';
UPDATE tickets SET created_at = '2024-09-13T19:12:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6797';
UPDATE tickets SET created_at = '2024-09-13T19:11:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6796';
UPDATE tickets SET created_at = '2024-09-13T19:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6795';
UPDATE tickets SET created_at = '2024-09-13T19:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6794';
UPDATE tickets SET created_at = '2024-09-13T19:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6793';
UPDATE tickets SET created_at = '2024-09-13T19:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6792';
UPDATE tickets SET created_at = '2024-09-13T19:06:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6791';
UPDATE tickets SET created_at = '2024-09-13T19:04:00.000Z'::timestamptz, duration_minutes = 30, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6790';
UPDATE tickets SET created_at = '2024-09-13T16:44:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6768';
UPDATE tickets SET created_at = '2024-09-13T16:42:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6767';
UPDATE tickets SET created_at = '2024-09-13T16:38:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6766';
UPDATE tickets SET created_at = '2024-09-13T16:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6765';
UPDATE tickets SET created_at = '2024-09-13T16:26:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6764';
UPDATE tickets SET created_at = '2024-09-13T16:17:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning S��ance de travail' WHERE jira_issue_key = 'OBCS-6763';
UPDATE tickets SET created_at = '2024-09-13T16:14:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6762';
UPDATE tickets SET created_at = '2024-09-13T16:13:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6761';
UPDATE tickets SET created_at = '2024-09-13T16:12:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6760';
UPDATE tickets SET created_at = '2024-09-13T16:11:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6759';
UPDATE tickets SET created_at = '2024-09-13T15:53:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6758';
UPDATE tickets SET created_at = '2024-09-13T15:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6757';
UPDATE tickets SET created_at = '2024-09-09T11:26:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6730';
UPDATE tickets SET created_at = '2024-09-08T15:40:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6725';
UPDATE tickets SET created_at = '2024-09-08T15:39:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6724';
UPDATE tickets SET created_at = '2024-09-08T15:38:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6723';
UPDATE tickets SET created_at = '2024-09-08T15:36:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6722';
UPDATE tickets SET created_at = '2024-09-08T15:36:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6721';
UPDATE tickets SET created_at = '2024-09-08T15:36:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6720';
UPDATE tickets SET created_at = '2024-09-08T15:35:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6719';
UPDATE tickets SET created_at = '2024-09-08T15:34:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6718';
UPDATE tickets SET created_at = '2024-09-08T15:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6717';
UPDATE tickets SET created_at = '2024-09-08T15:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6716';
UPDATE tickets SET created_at = '2024-09-08T15:32:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6715';
UPDATE tickets SET created_at = '2024-09-08T15:32:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6714';
UPDATE tickets SET created_at = '2024-09-08T15:31:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6713';
UPDATE tickets SET created_at = '2024-09-08T15:31:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6712';
UPDATE tickets SET created_at = '2024-09-08T15:31:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6711';
UPDATE tickets SET created_at = '2024-09-08T15:24:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6705';
UPDATE tickets SET created_at = '2024-09-08T15:18:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6702';
UPDATE tickets SET created_at = '2024-09-08T15:18:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6701';
UPDATE tickets SET created_at = '2024-09-08T15:17:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6700';
UPDATE tickets SET created_at = '2024-09-08T15:16:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6699';
UPDATE tickets SET created_at = '2024-09-08T15:15:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6698';
UPDATE tickets SET created_at = '2024-09-08T10:24:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6697';
UPDATE tickets SET created_at = '2024-09-08T10:20:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6695';
UPDATE tickets SET created_at = '2024-09-08T10:17:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6694';
UPDATE tickets SET created_at = '2024-09-06T19:10:00.000Z'::timestamptz, duration_minutes = 160, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6688';
UPDATE tickets SET created_at = '2024-09-06T19:08:00.000Z'::timestamptz, duration_minutes = 120, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6687';
UPDATE tickets SET created_at = '2024-09-06T19:07:00.000Z'::timestamptz, duration_minutes = 60, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6686';
UPDATE tickets SET created_at = '2024-09-06T19:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6685';
UPDATE tickets SET created_at = '2024-09-06T19:03:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6684';
UPDATE tickets SET created_at = '2024-09-06T19:03:00.000Z'::timestamptz, duration_minutes = 27, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6683';
UPDATE tickets SET created_at = '2024-09-06T18:59:00.000Z'::timestamptz, duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6682';
UPDATE tickets SET created_at = '2024-09-06T18:53:00.000Z'::timestamptz, duration_minutes = 120, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6681';
UPDATE tickets SET created_at = '2024-09-06T18:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6680';
UPDATE tickets SET created_at = '2024-09-06T18:51:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6679';
UPDATE tickets SET created_at = '2024-09-06T18:50:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6678';
UPDATE tickets SET created_at = '2024-09-06T18:47:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6677';
UPDATE tickets SET created_at = '2024-09-06T18:45:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6676';
UPDATE tickets SET created_at = '2024-09-06T18:45:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6675';
UPDATE tickets SET created_at = '2024-09-06T18:44:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6674';
UPDATE tickets SET created_at = '2024-09-06T18:41:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6673';
UPDATE tickets SET created_at = '2024-09-05T11:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6666';
UPDATE tickets SET created_at = '2024-09-05T11:10:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6665';
UPDATE tickets SET created_at = '2024-09-05T11:09:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6664';
UPDATE tickets SET created_at = '2024-09-02T19:05:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6652';
UPDATE tickets SET created_at = '2024-09-02T17:11:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6651';
UPDATE tickets SET created_at = '2024-09-02T17:05:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6650';
UPDATE tickets SET created_at = '2024-09-02T17:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6649';
UPDATE tickets SET created_at = '2024-09-02T11:49:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6645';
UPDATE tickets SET created_at = '2024-09-01T17:40:00.000Z'::timestamptz, duration_minutes = 60, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6637';
UPDATE tickets SET created_at = '2024-09-01T17:39:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6636';
UPDATE tickets SET created_at = '2024-09-01T17:38:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6635';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-6634';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6633';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6632';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-6631';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6630';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6629';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6628';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6627';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6626';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6617';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6616';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6615';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6614';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6613';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6612';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6611';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6610';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6609';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6608';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6607';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6606';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6602';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6601';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6600';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6597';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6596';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6566';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6560';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6546';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6545';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6544';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6543';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6542';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6536';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6534';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6533';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6532';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6531';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6530';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6529';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6528';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6527';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6526';
UPDATE tickets SET duration_minutes = 17, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6525';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6524';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6523';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6522';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6521';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6520';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6519';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6518';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6517';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6516';
UPDATE tickets SET duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6515';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6514';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6512';
UPDATE tickets SET duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6506';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6504';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6503';
UPDATE tickets SET duration_minutes = 2 WHERE jira_issue_key = 'OBCS-6501';
UPDATE tickets SET duration_minutes = 60, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Présentation' WHERE jira_issue_key = 'OBCS-6500';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6495';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6490';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6489';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6488';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6487';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6486';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6484';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6483';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6482';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6473';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6470';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6468';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6467';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6466';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6444';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6442';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6438';
UPDATE tickets SET duration_minutes = 65, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6437';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6432';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6431';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6417';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6416';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6414';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6413';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6409';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6408';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6407';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6406';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6405';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6404';
UPDATE tickets SET duration_minutes = 10, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6403';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6402';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6401';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6400';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6399';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Revue des Accès/Workflows', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6391';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6390';
UPDATE tickets SET duration_minutes = 15 WHERE jira_issue_key = 'OBCS-6389';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6388';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Requête en cours' WHERE jira_issue_key = 'OBCS-6387';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6386';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Redirection vers ressources OBC', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-6385';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6384';
UPDATE tickets SET duration_minutes = 13, action_menee = 'Explication en ligne', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-6383';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Relance sur Bug en cours' WHERE jira_issue_key = 'OBCS-6382';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6381';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6380';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6379';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6369';
UPDATE tickets SET duration_minutes = 60, action_menee = 'Séance Google Meet/Zoom', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6362';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6361';
UPDATE tickets SET duration_minutes = 12, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6360';
UPDATE tickets SET duration_minutes = 15, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6358';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6357';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6356';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6355';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6354';
UPDATE tickets SET duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6348';
UPDATE tickets SET duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6347';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6346';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6345';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6344';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6342';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6341';
UPDATE tickets SET duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6340';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6339';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6334';
UPDATE tickets SET duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6332';
UPDATE tickets SET duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6331';
UPDATE tickets SET duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6330';
UPDATE tickets SET duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6326';
UPDATE tickets SET duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6325';
UPDATE tickets SET duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6324';
UPDATE tickets SET created_at = '2024-07-30T17:30:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6319';
UPDATE tickets SET created_at = '2024-07-30T17:28:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6318';
UPDATE tickets SET created_at = '2024-07-30T17:27:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6317';
UPDATE tickets SET created_at = '2024-07-30T17:27:00.000Z'::timestamptz, duration_minutes = 6, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6316';
UPDATE tickets SET created_at = '2024-07-30T17:19:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6315';
UPDATE tickets SET created_at = '2024-07-30T17:18:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6314';
UPDATE tickets SET created_at = '2024-07-30T17:16:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6313';
UPDATE tickets SET created_at = '2024-07-30T11:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6312';
UPDATE tickets SET created_at = '2024-07-30T11:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6311';
UPDATE tickets SET created_at = '2024-07-30T11:48:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6308';
UPDATE tickets SET created_at = '2024-07-30T09:17:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6305';
UPDATE tickets SET created_at = '2024-07-30T09:02:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6304';
UPDATE tickets SET created_at = '2024-07-30T09:01:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6303';
UPDATE tickets SET created_at = '2024-07-29T18:37:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6302';
UPDATE tickets SET created_at = '2024-07-29T18:36:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6301';
UPDATE tickets SET created_at = '2024-07-29T18:34:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6300';
UPDATE tickets SET created_at = '2024-07-29T18:33:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6299';
UPDATE tickets SET created_at = '2024-07-29T18:33:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6298';
UPDATE tickets SET created_at = '2024-07-29T08:53:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6294';
UPDATE tickets SET created_at = '2024-07-29T08:52:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6293';
UPDATE tickets SET created_at = '2024-07-26T17:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6273';
UPDATE tickets SET created_at = '2024-07-26T17:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6272';
UPDATE tickets SET created_at = '2024-07-26T17:07:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6271';
UPDATE tickets SET created_at = '2024-07-26T16:52:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6266';
UPDATE tickets SET created_at = '2024-07-26T16:48:00.000Z'::timestamptz, duration_minutes = 9, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6265';
UPDATE tickets SET created_at = '2024-07-26T16:42:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6263';
UPDATE tickets SET created_at = '2024-07-26T16:42:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6262';
UPDATE tickets SET created_at = '2024-07-26T16:32:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6261';
UPDATE tickets SET created_at = '2024-07-26T16:31:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6260';
UPDATE tickets SET created_at = '2024-07-26T11:54:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6259';
UPDATE tickets SET created_at = '2024-07-26T11:53:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6258';
UPDATE tickets SET created_at = '2024-07-26T11:51:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6257';
UPDATE tickets SET created_at = '2024-07-25T18:37:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6256';
UPDATE tickets SET created_at = '2024-07-25T18:29:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6255';
UPDATE tickets SET created_at = '2024-07-25T18:28:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6254';
UPDATE tickets SET created_at = '2024-07-25T18:25:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6253';
UPDATE tickets SET created_at = '2024-07-25T18:23:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6252';
UPDATE tickets SET created_at = '2024-07-25T18:23:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6251';
UPDATE tickets SET created_at = '2024-07-25T18:21:00.000Z'::timestamptz, duration_minutes = 7, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6250';
UPDATE tickets SET created_at = '2024-07-25T18:20:00.000Z'::timestamptz, duration_minutes = 11, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6249';
UPDATE tickets SET created_at = '2024-07-25T18:19:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6248';
UPDATE tickets SET created_at = '2024-07-25T18:19:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6247';
UPDATE tickets SET created_at = '2024-07-25T18:15:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6246';
UPDATE tickets SET created_at = '2024-07-25T18:13:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6245';
UPDATE tickets SET created_at = '2024-07-25T18:10:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6244';
UPDATE tickets SET created_at = '2024-07-25T18:10:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6243';
UPDATE tickets SET created_at = '2024-07-25T18:09:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6242';
UPDATE tickets SET created_at = '2024-07-25T18:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6241';
UPDATE tickets SET created_at = '2024-07-25T18:08:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6240';
UPDATE tickets SET created_at = '2024-07-25T12:42:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6238';
UPDATE tickets SET created_at = '2024-07-25T11:16:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6237';
UPDATE tickets SET created_at = '2024-07-25T10:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6235';
UPDATE tickets SET created_at = '2024-07-25T10:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6234';
UPDATE tickets SET created_at = '2024-07-25T10:44:00.000Z'::timestamptz, duration_minutes = 13 WHERE jira_issue_key = 'OBCS-6233';
UPDATE tickets SET created_at = '2024-07-23T16:19:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Autres (Précisez dans la description)', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6227';
UPDATE tickets SET created_at = '2024-07-23T16:07:00.000Z'::timestamptz, duration_minutes = 60, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6226';
UPDATE tickets SET created_at = '2024-07-23T16:05:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6225';
UPDATE tickets SET created_at = '2024-07-23T16:04:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6224';
UPDATE tickets SET created_at = '2024-07-23T16:03:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6223';
UPDATE tickets SET created_at = '2024-07-23T12:14:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6221';
UPDATE tickets SET created_at = '2024-07-23T11:43:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6220';
UPDATE tickets SET created_at = '2024-07-23T11:40:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6219';
UPDATE tickets SET created_at = '2024-07-22T18:55:00.000Z'::timestamptz, duration_minutes = 32, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6212';
UPDATE tickets SET created_at = '2024-07-22T14:38:00.000Z'::timestamptz, duration_minutes = 1 WHERE jira_issue_key = 'OBCS-6209';
UPDATE tickets SET created_at = '2024-07-22T14:33:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6208';
UPDATE tickets SET created_at = '2024-07-22T14:31:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6207';
UPDATE tickets SET created_at = '2024-07-22T11:15:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6204';
UPDATE tickets SET created_at = '2024-07-22T11:14:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6203';
UPDATE tickets SET created_at = '2024-07-22T11:13:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6202';
UPDATE tickets SET created_at = '2024-07-22T11:11:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6201';
UPDATE tickets SET created_at = '2024-07-21T15:46:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6198';
UPDATE tickets SET created_at = '2024-07-21T15:45:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6197';
UPDATE tickets SET created_at = '2024-07-21T15:44:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6196';
UPDATE tickets SET created_at = '2024-07-21T15:41:00.000Z'::timestamptz, duration_minutes = 42, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6195';
UPDATE tickets SET created_at = '2024-07-21T15:40:00.000Z'::timestamptz, duration_minutes = 4, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6194';
UPDATE tickets SET created_at = '2024-07-21T15:40:00.000Z'::timestamptz, duration_minutes = 0, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6193';
UPDATE tickets SET created_at = '2024-07-21T15:40:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Assistance' WHERE jira_issue_key = 'OBCS-6192';
UPDATE tickets SET created_at = '2024-07-20T18:09:00.000Z'::timestamptz, duration_minutes = 3, action_menee = 'Explication en ligne', objet_principal = 'Planning Séance de travail' WHERE jira_issue_key = 'OBCS-6182';
UPDATE tickets SET created_at = '2024-07-20T18:07:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6181';
UPDATE tickets SET created_at = '2024-07-20T18:06:00.000Z'::timestamptz, duration_minutes = 5, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6179';
UPDATE tickets SET created_at = '2024-07-20T18:01:00.000Z'::timestamptz, duration_minutes = 1, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6177';
UPDATE tickets SET created_at = '2024-07-20T17:56:00.000Z'::timestamptz, duration_minutes = 2, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6176';
UPDATE tickets SET created_at = '2024-07-20T17:55:00.000Z'::timestamptz, duration_minutes = 8, action_menee = 'Explication en ligne', objet_principal = 'Autres' WHERE jira_issue_key = 'OBCS-6175';
