-- OnpointDoc - Import des tickets d'assistance depuis "all assistance.csv"
-- Date: 2025-12-10
-- Partie 15 sur 15 (203 tickets)
-- Utilise la clé OBCS-XXXXX pour éviter les doublons (ON CONFLICT)

-- ============================================
-- ÉTAPE 1: Créer la table temporaire
-- ============================================

CREATE TEMP TABLE IF NOT EXISTS temp_assistance_tickets (
  jira_issue_key TEXT NOT NULL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  reporter_name TEXT,
  client_name TEXT,
  contact_user_name TEXT,
  job_title TEXT,
  module_name TEXT,
  submodule_name TEXT,
  canal TEXT,
  priority TEXT,
  status TEXT,
  duration_minutes DECIMAL(10,2),
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  action_menee TEXT,
  objet_principal TEXT
);

-- ============================================
-- ÉTAPE 2: Insérer les données dans la table temporaire
-- ============================================

INSERT INTO temp_assistance_tickets (
  jira_issue_key,
  title,
  description,
  reporter_name,
  client_name,
  contact_user_name,
  job_title,
  module_name,
  submodule_name,
  canal,
  priority,
  status,
  duration_minutes,
  created_at,
  updated_at,
  action_menee,
  objet_principal
) VALUES
  (
    'OBCS-2126',
    'Assistance - Explication en ligne - DIRECTEUR TECHNIQUE ADJOINT',
    'ASSISTANCE CONNEXION OBC',
    'N''GBRA MOYE BERNICE DORIS',
    'WATSAN',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.53,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2125',
    'Assistance - Explication en ligne - DIRECTEUR TECHNIQUE ADJOINT',
    'ASSISTANCE SUR CONNEXION OBC',
    'N''GBRA MOYE BERNICE DORIS',
    'WATSAN',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.30,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2124',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'INFO SUR ASSISTANCE EN PRESENTIEL A FAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.40,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2123',
    'Présentation - Explication en ligne - Directeur Logistique',
    'INFORMATION SUR PROGRAMMATION DE PRESENTATION',
    'N''GBRA MOYE BERNICE DORIS',
    'ENVAL LABORATOIRE',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.31,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Présentation'
  ),
  (
    'OBCS-2122',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE PARAMETRAGE SALAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    11.40,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2121',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE OPERATION DE CAISSE',
    'N''GBRA MOYE BERNICE DORIS',
    'MYKA',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.10,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2120',
    'Assistance - Explication en ligne - Chef de Projet',
    'Accès aux fonctionnalités',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.30,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2119',
    'Assistance - Explication en ligne - Directeur Logistique',
    'CALL POUR ASSISTANCE CONNEXION POUR LA SEANCE EN LIGNE',
    'N''GBRA MOYE BERNICE DORIS',
    'ENVAL LABORATOIRE',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.50,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2118',
    'Assistance - Explication en ligne - Responsable IT',
    'ASSISTANCE SUR CREATION DE COMPTE UTILISATEURS',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.54,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2117',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'SUPPRESSION DE BASE TEST - SUPPRESSION DE BASE TEST POUR GO LIVE',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.19,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-2116',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Retour sur évolution traitement requête',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    5.50,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2115',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Relance requête en cours de traitement',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    3.30,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2114',
    'Assistance - Explication en ligne - Comptable',
    'Relance requête',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.46,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2113',
    'Assistance - Séance Google Meet/Zoom - ADMINISTRATRICE',
    'Formation google meet (immo, achat, vente, RH)',
    'JOEL SIE',
    'FIRST CAPITAL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Online (Google Meet, Teams...)',
    NULL,
    'Terminé',
    90.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Séance Google Meet/Zoom',
    'Assistance'
  ),
  (
    'OBCS-2112',
    'Assistance - Explication en ligne - Comptable',
    'LE PARAMETRAGE DE COMPTABILISATION CREE EN DOUBLE',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2111',
    'Assistance - Explication en ligne - Comptable',
    'VERIFICATION DES COMPTES TIERS QUI NE SE DEVERSES PAS',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2110',
    'Assistance - Explication en ligne - Comptable',
    'LES COMPTES TIERS NE SE DEVERSES PAS POUR LE COMPTES 4081',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2109',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Relance sur l''implementation de l''avance',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2108',
    'Assistance - Explication en ligne - Comptable',
    'Rectification de l''écriture a partir des factures ventes ( Recherche de la facture a partir de la date, Edition',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    14.40,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2107',
    'Assistance - Explication en ligne - Comptable',
    'Correction opérations dans le grand livre - Compte 411000',
    'EVA BASSE',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.46,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2106',
    'Assistance - Explication en ligne - Comptable',
    'Explication état traitement de requête',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    14.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2105',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Relance correction écritures comptable',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel WhatsApp',
    NULL,
    'Terminé',
    6.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2104',
    'Assistance - Explication en ligne - Comptable',
    'Demande d''assistance online',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2103',
    'Assistance - Explication en ligne - Comptable',
    'Interrogation écriture - Suite interaction précédente',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    1.90,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2102',
    'Assistance - Explication en ligne - Comptable',
    'Suite interaction',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    2.44,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2101',
    'Assistance - Explication en ligne - Comptable',
    'Correction écriture manuelle',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    3.00,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2100',
    'Assistance - Explication en ligne - Comptable',
    'Correction compte de tiers / Facture / Ecritures',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    2.59,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    '2024-06-19T09:59:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2099',
    'Assistance - Explication en ligne - Comptable',
    'Suite correction écriture',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    6.10,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2098',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'Demande d''information - Correction opération',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.31,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2097',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR IMPORT DE JOURNAUX',
    'N''GBRA MOYE BERNICE DORIS',
    'MYKA',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.27,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2096',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR SUPPRESION FACTURE VENTE',
    'N''GBRA MOYE BERNICE DORIS',
    'MYKA',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.70,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2095',
    'Assistance - Explication en ligne - Comptable',
    'CALL POUR SEANCE EN LIGNE A 16H',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.25,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2094',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'ASSISTANCE POUR AVOIR LE RAPPORT D''ACTIVITE DE 2022 SUR TOUS LES UTILISATEURS',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.40,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2093',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR SE CONNECTER POUR LA SEANCE EN LIGNE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.19,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2092',
    'Relance sur Bug en cours - Explication en ligne - Comptable',
    'ASSISTANCE SUR BUG TRAITE',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.46,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2091',
    'Assistance - Explication en ligne - Comptable',
    'Explication sur pourquoi utiliser un compte tiers retention au lieu de plusieurs compte généraux',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2090',
    'Assistance - Explication en ligne - Comptable',
    'Les comptes de la retention à créer en tiers',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    21.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2089',
    'Assistance - Explication en ligne - Comptable',
    'Enregistrement de nature de prestation immobilisation',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2088',
    'Assistance - Explication en ligne - Chef de Projet',
    'Suivi workflow - Requête suivi par la suite par Mr Vivien D',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    1.42,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2087',
    'Assistance - Explication en ligne - Comptable',
    'Un projet qui ne se deverses pas',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2086',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'ASSISTANCE SUR SAISIE COMPTABLE',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Chat SMS',
    NULL,
    'Terminé',
    10.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2085',
    'Assistance - Explication en ligne - Comptable',
    'Nombre de chiffre après la virgule',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    11.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2084',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'ASSISTANCE SAISIE BON DE COMMANDE',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.11,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2083',
    'Relance sur Bug en cours - Explication en ligne - Comptable',
    'BUG EN COURS DE TRAITEMENT',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.45,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2082',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'ASSISTANCE UTILISATION OBC',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Chat SMS',
    NULL,
    'Terminé',
    45.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2081',
    'Relance sur Bug en cours - Explication en ligne - Contrôleur de gestion',
    'ASSISTANCE POUR LE BUG TRAITE EN PLUSIEURS JOURS',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.40,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2080',
    'Assistance - Explication en ligne - Directeur Logistique',
    'ASSISTANCE POUR PARAMETRAGE COMPTE UTILISATEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'ENVAL LABORATOIRE',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.25,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2079',
    'Relance sur Bug en cours - Redirection vers ressources OBC - Comptable',
    'TRAITEMENT DE BUG A FAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.46,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Redirection vers ressources OBC',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2078',
    'Relance sur Bug en cours - Redirection vers ressources OBC - Comptable',
    'BUG RENCONTRE DANS LE COMPTE FOURNISSEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.15,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Redirection vers ressources OBC',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2077',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE MAIL UTILISATEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.45,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2076',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE SUR COMPTABILITE ANALYTIQUE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    20.12,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2075',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE CALCUL DE PAIE JUIN',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    18.48,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2074',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE CALCUL PAIE JUIN',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    8.33,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2073',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR RELANCE CLIENT IMPAYE',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.09,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2072',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'ASSISATNCE RAPPORT FOURNISSEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.31,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2071',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'ASSISTANCE SUR ENREGISTREMENT FACTURE ACHAT',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.43,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2070',
    'Assistance - Explication en ligne - Directeur Commercial et Marketing',
    'CALL POUR PRENDRE DE SES NOUVELLES VU SON REPOS MALADIE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.51,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2069',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR GRAND LIVRE ACHAT',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.44,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2068',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE COMPTABILITE ANALYTIQUE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    15.37,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2067',
    'Assistance - Explication en ligne - Comptable',
    'Paramétrage comptabilisation de la paie - Rappel + détaille par Chat WhatsApp',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2066',
    'Assistance - Explication en ligne - Comptable',
    'Accès fonctionnalité Import / Export client & fournisseur',
    'Edwidge Kouassi',
    'PROPERTY KRO',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    53.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2065',
    'Autres - Autres (Précisez dans la description) - Comptable',
    'Information - Envoi du point des paramétrage',
    'JOEL SIE',
    'LABOGEM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-2064',
    'Assistance - Explication en ligne - Comptable',
    'Il n''arrive pas à valider une requete',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2063',
    'Assistance - Explication en ligne - Comptable',
    'Revoir le parametrage de comptabilisation de la paie',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2062',
    'Autres - Explication en ligne - Chef du Département des Affaires Juridiques, du Contentieux et des Ressources Humaines',
    'Relance recueil données comptable',
    'Edwidge Kouassi',
    'CILAGRI',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.37,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-2061',
    'Assistance - Explication en ligne - Comptable',
    'Demande d''information - Fichier du personnel',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    5.20,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2060',
    'Assistance - Explication en ligne - Comptable',
    'Recueil d''information',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.32,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2059',
    'Relance sur Requête en cours - Explication en ligne - Assistant(e) RH',
    'Validation bon de commande - Révision paramétrage Workflows',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    5.20,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2058',
    'Assistance - Explication en ligne - Chef de Projet',
    'Validation Bon de commande',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    10.35,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2057',
    'Assistance - Explication en ligne - Comptable',
    'Demande d''exportation base client',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.30,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2056',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Confirmation RDV',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.54,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2055',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Réinitialisation Base client OBC',
    'Edwidge Kouassi',
    'PROPERTY KRO',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.60,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2054',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Réinitialisation Base client OBC',
    'Edwidge Kouassi',
    'PROPERTY KRO',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.22,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2053',
    'Assistance - Explication en ligne - Comptable',
    'Relance rendez-vous - Faire un mail de proposition de date',
    'Edwidge Kouassi',
    'CEMT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.50,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2052',
    'Assistance - Explication en ligne - Comptable',
    'Demande de remise à niveau - Fera suivre l''appel par un mail récap',
    'Edwidge Kouassi',
    'PROPERTY KRO',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.40,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2051',
    'Assistance - Explication en ligne - Comptable',
    'Poursuite correction écritures comptable',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.25,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2050',
    'Relance sur Requête en cours - Explication en ligne - Gestionnaire de stock',
    'Relance pour requete sur le bordereau de retour',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2049',
    'Assistance - Explication en ligne - Comptable',
    'Comment générer automatiquement les impots et taxes',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2048',
    'Assistance - Explication en ligne - Comptable',
    'Explication pour générer les écritures de paie',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    11.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2047',
    'Assistance - Autres (Précisez dans la description) - Comptable',
    'Relance sur le bug lié au bordereau de retour - Appel du vendredi',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-2046',
    'Relance sur Requête en cours - Explication en ligne - Chef de Projet',
    'Etat d''avancement requête',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    14.57,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-2045',
    'Assistance - Explication en ligne - Télésales',
    'Retour appel en absence - Confirmation rendez vous',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.90,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2044',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE SUR LA CAISSE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    21.37,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2043',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SAISIE CAISSE ET ECRITURE MANUELLE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.57,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2042',
    'Assistance - Explication en ligne - Responsable achat - logistique',
    'ASSISTANCE GESTION DE STOCK',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.36,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2041',
    'Assistance - Explication en ligne - Responsable achat - logistique',
    'ASSISTANCE GESTION DE STOCK',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.20,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2040',
    'Assistance - Explication en ligne - Responsable achat - logistique',
    'ASSISTANCE GESTION DE STOCK',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.50,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2039',
    'Assistance - Explication en ligne - Assistant(e) des marchés',
    'Revoir les données saisies et la TVA qui ne s''affiche pas automatiquement',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2038',
    'Assistance - Explication en ligne - Assistant(e) des marchés',
    'Le montant de la TVA qui ne s''affiche pas automatiquement',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2037',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE SUR IMPOT ET TAXES',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.17,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2036',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE SUR SAISIE IMPOT ET TAXES',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.44,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2035',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE SUR ECRITURES MANUELLES LIEES AUX PROJET',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    16.60,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2034',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE COMPTABILITE ANALYTIQUE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.50,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2033',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR SAISIE COMPTABLE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.70,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2032',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SAISIE COMPTABILITE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.10,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2031',
    'Assistance - Explication en ligne - Responsable IT',
    'ASSISTANCE SUR ACCES WORKFLOW',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.11,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2030',
    'Assistance - Explication en ligne - Responsable IT',
    'ASSISTANCE POUR CREATION ACCES DE NOUVEL UTILISATEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.27,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2029',
    'Autres - Explication en ligne - Comptable',
    'CALL POUR AVOIR LEUR AVIS SUR DES ELEMENTS DU PARAMATRE TIERS FOURNISSEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'VENUS DISTRIBUTION',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.46,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-2028',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'ASSISTANCE SUR PARAMETRAGE HEURE SUPPELEMENTAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.38,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2027',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'ASSISTANCE SUR INTEGRATION ''HEURE SUPPLEMENTAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.70,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2026',
    'Assistance - Explication en ligne - Comptable',
    'Suite conversation par WhatsApp - Réception capture écran et détaille',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Chat WhatsApp',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2025',
    'Assistance - Explication en ligne - Comptable',
    'Demande d''information détaillé',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.37,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2024',
    'Assistance - Explication en ligne - Comptable',
    'Génération écriture de paie / Contrôle paramétrage',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    8.56,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2023',
    'Assistance - Explication en ligne - Comptable',
    'Demander une information liée au budget',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    11.00,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2022',
    'Assistance - Explication en ligne - Comptable',
    'Absence d''écriture de paie - Grand livre',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.48,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    '2024-06-19T09:58:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2021',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Livre de paie',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.26,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2020',
    'Assistance - Explication en ligne - Assistant(e) Comptable',
    'Accusé de réception poste comptable Tiers',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    9.23,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2019',
    'Assistance - Explication en ligne - Caissier(ère)',
    'Retour confirmation gestion des accès',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.32,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2018',
    'Assistance - Explication en ligne - Comptable',
    'MAJ accès Paramétrage comptabilisation des natures de prestation',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.54,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2017',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'ASSISTACE SUR HEURES SUPPLEMENTAIRES A METTRE DANS LE CALCUL DE SALAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.22,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2016',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE SUR LES LIVRES COMPTABLES ET COMPTABILITE ANALYTIQUE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    9.10,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2015',
    'Assistance - Explication en ligne - Comptable',
    'Informer pour l''enregistrement d''un département',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2014',
    'Assistance - Explication en ligne - Comptable',
    'AJOUTER UN DEPARTEMENT AFIN DE FAIRE DES IMPUTATIONS',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2013',
    'Relance sur Bug en cours - Explication en ligne - Directeur Administratif et Financier',
    'Relance pour une requette liée à au plan comptable général',
    'JOEL SIE',
    'EJARA',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2012',
    'Autres - Explication en ligne - Comptable',
    'Proposition date de rendez-vous',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.36,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-2011',
    'Assistance - Explication en ligne - Comptable',
    'Confirmation rendez-vous',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.14,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2010',
    'Autres - Explication en ligne - Chef de Projet',
    'Prise de rendez-vous Gouvernance',
    'Edwidge Kouassi',
    'CEMT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.47,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-2009',
    'Assistance - Explication en ligne - Assistant(e) Comptable',
    'Info envoi de N° poste comptable tiers (11 comptes)',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.42,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2008',
    'Autres - Autres (Précisez dans la description) - Chef de Projet',
    'Prise de rendez vous - Achat import - Schématisation processus métier',
    'Edwidge Kouassi',
    'ARIC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.90,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-2007',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'ASSISTANCE CALCUL DE PAIE FEVRIER 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    32.20,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2006',
    'Assistance - Explication en ligne - Directeur Administratif et Financier',
    'ASSISTANCE CALCUL SALAIRE FEVRIER 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    31.16,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2005',
    'Relance sur Bug en cours - Explication en ligne - Comptable',
    'CALL POUR BUG TRAITE AVEC SUCCES',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.20,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2004',
    'Relance sur Bug en cours - Explication en ligne - Comptable',
    'CALL POUR TRAITEMENT DE BUG EN LIGNE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    11.40,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-2003',
    'Assistance - Explication en ligne - Chef de Projet',
    'Liaison et mise en forme formulaire - Intégration formulaire type - exemplaire envoyé par whatS',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    6.26,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2002',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR LA SAISIE DE CAISSE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.23,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2001',
    'Assistance - Explication en ligne - Chef de Projet',
    'Suite',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    12.59,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-2000',
    'Assistance - Explication en ligne - Chef de Projet',
    'Assistance - Relance schématisation',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.50,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1999',
    'Autres - Explication en ligne - Comptable',
    'Relance recueil de données',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.55,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1998',
    'Assistance - Explication en ligne - Comptable',
    'Suite - Recherche et résolution requête client - Mauvaise liaison des comptes de tiers',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    6.54,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1997',
    'Assistance - Explication en ligne - Comptable',
    'Résolution et explication en ligne - Ecriture comptable (2 Appels sortant)',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    8.59,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1996',
    'Assistance - Explication en ligne - Comptable',
    'Explication en ligne enregistrement achat import',
    'JOEL SIE',
    'KORI TRANSPORT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1995',
    'Assistance - Explication en ligne - Comptable',
    'Explication En ligne traitement comptable / Ecriture - Echange message WhatsApp',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel WhatsApp',
    NULL,
    'Terminé',
    45.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1994',
    'Autres - Autres (Précisez dans la description) - Gestionnaire/Responsable Parc Automobile',
    'Relance pour un rendez-vous - Prise de rendez-vous',
    'JOEL SIE',
    'ITC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-1993',
    'Assistance - Explication en ligne - Assistant(e) Comptable',
    'Vérification et contrôle des facture - Contrôle des encaissement - Conclusion résolution requête : Certaine Facture client dites invisible lors de l''encaissement avaient été encaissé par le responsable (3 appels sortant pour la même raison - 34s, 5.44 et 2.31)',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    8.49,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1992',
    'Assistance - Explication en ligne - Assistant(e) Comptable',
    'Absence de facture lors de l''encaissement client',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1991',
    'Autres - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'A regarder - Problème d''édition des postes comptable de la classe 5',
    'JOEL SIE',
    'EJARA',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-1990',
    'Assistance - Autres (Précisez dans la description) - Assistant(e) RH',
    'Editer entité et modifier nombre de jour acquis - Mise à jour du nombre de jour acquis',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1989',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE SUR BON DE COMMANDE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Chat WhatsApp',
    NULL,
    'Terminé',
    20.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1988',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE POUR SAISIE D''OPERATION DE BON DE COMMANDE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    8.30,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1987',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR SAISIE COMPTABLE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.42,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1986',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR SAISIE CAISSE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.33,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1985',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR SAISIE COMPTABLE A REFAIRE',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.45,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1984',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'CALL POUR PARAMETRAGE DE NOUVEL UTILISATEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.58,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-1983',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE COMPTABILITE SUR LES SAISIES COMPTABLES',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.45,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1982',
    'Autres - Explication en ligne - Assistant(e) / Stagiaire',
    'Retour client- Confirmation Date et heure',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.52,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1981',
    'Autres - Explication en ligne - Assistant(e) / Stagiaire',
    'Confirmation séance de formation',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.46,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1980',
    'Assistance - Explication en ligne - Assistant(e) Technique',
    'Resolution de la mauvaise saisie de l''expression de besoin',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1979',
    'Assistance - Explication en ligne - Assistant(e) Technique',
    'Enregistrement d''une expression de bésoin tournant en boucle dû à une saisie ex:(1/2)',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1978',
    'Assistance - Explication en ligne - Comptable',
    'Demande d''actualisation du compte ou de redémarrage',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    0.54,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1977',
    'Assistance - Explication en ligne - Comptable',
    'Impossible de se connecter (Erreur serveur déjà résolu)',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.41,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1976',
    'Assistance - Explication en ligne - Comptable',
    'APPEL POUR ASSISTANCE SUR BALANCE COMPTABLE',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.28,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1975',
    'Assistance - Explication en ligne - Comptable',
    'APPEL POUR ASSISTANCE SUR BALANCE COMPTABLE',
    'N''GBRA MOYE BERNICE DORIS',
    'FALCON',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.31,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1974',
    'Autres - Explication en ligne - Directeur Technique Adjoint',
    'APPEL POUR SERVEUR ERROR RENCONTRE ET PRISE DE RENDEZ VOUS',
    'N''GBRA MOYE BERNICE DORIS',
    'WATSAN',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.12,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1973',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage RH en ligne salaire janvier 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    33.27,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1972',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage RH en ligne salaire janvier 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    10.38,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1971',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage RH en ligne salaire Janvier 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.50,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1970',
    'Assistance - Explication en ligne - Comptable',
    'Demande d''informations - Document à fournir pour paramétrage ( appel reçu dont 1 pour les demandes d''informations & 1 pour la confirmation de réception)',
    'Edwidge Kouassi',
    'CILAGRI',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.28,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1969',
    'Relance sur Requête en cours - Autres (Précisez dans la description) - Comptable',
    'Instruction & Résolution online - Suppression de facture, programmation de règlement et règlement associé',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.21,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-1968',
    'Autres - Explication en ligne - Comptable',
    'Lorsque qu''une année comptable est sélectionnée, permettre uniquement que les données enregistré dans le courant de celle-ci soit possible, bloquer et renvoyer une notification à l''utilisateur stipulant que l''année d''enregistrement sélectionné n''est pas valide.',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1967',
    'Assistance - Explication en ligne - Chef de Projet',
    'Demande d''assistance enregistrement processus métier',
    'Edwidge Kouassi',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1966',
    'Autres - Explication en ligne - Assistant(e) Comptable',
    'Prise de contact et point récap état des paramétrages',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.11,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1965',
    'Autres - Autres (Précisez dans la description) - Comptable',
    'Passation charge - Récup données paramétrage - Mise en relation - Chef comptable intérimaire',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Chat WhatsApp',
    NULL,
    'Terminé',
    6.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-1964',
    'Autres - Explication en ligne - Intérimaire chef comptable',
    'Explication besoin (Données de paramétrage)',
    'Edwidge Kouassi',
    'AFRIC FONCIER',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.20,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1963',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR L''ETAT D''AVANCEMENT DES IMPORTATIONS COMPTABLES 2021/2020',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.33,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1962',
    'Assistance - Explication en ligne - Comptable',
    'ASSISANTANCE POUR RECEVOIR LE MAIL D''UN NOUVEL UTILISATEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.40,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1961',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE SUR ENREGISTREMENT DE CONTRAT DE TRAVAIL OHADA',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.16,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1960',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE SUR ENREGISTREMENT DE CONTRAT DE TRAVAIL OHADA',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.44,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1959',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'ASSISTANCE SUR L''ENREGISTREMENT DE CONTRAT DE TRAVAIL OHADA',
    'N''GBRA MOYE BERNICE DORIS',
    'EGBV',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.19,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1958',
    'Relance sur Bug en cours - Autres (Précisez dans la description) - Chef de Projet',
    'ASSISTANCE POUR BUG RENCONTRE SUR EXPRESSION DE BESOIN',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.21,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Relance sur Bug en cours'
  ),
  (
    'OBCS-1957',
    'Assistance - Explication en ligne - Chef de Projet',
    'ASSISTANCE POUR L''ERREUR FAITE DANS LEUR SAISIE DE BUDGET DEPENSE',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.17,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1956',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR INTEGRER SON MAIL DANS LE WORKFLOW EXECUTION DE PAIEMENT FOURNISSEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.49,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1955',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE POUR INTEGRER SON MAIL DANS LE WORKFLOW EXECUTION DE PAIEMENT FOURNISSEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.41,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1954',
    'Assistance - Explication en ligne - Comptable',
    'ASSISTANCE SUR LA PROGRAMMATION FOURNISSEUR',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.20,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1953',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage en ligne RH SALAIRE JANVIER 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    40.46,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1952',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage en ligne RH SALAIRE JANVIER 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.46,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1951',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage en ligne RH SALAIRE JANVIER 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    6.54,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1950',
    'Assistance - Explication en ligne - Comptable',
    'Comment saisir et transferer le RAN',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    13.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1949',
    'Autres - Autres (Précisez dans la description) - Assistant(e) RH',
    'Un bug constaté - Impossible d''éditer un fichier du personnel',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-1948',
    'Assistance - Explication en ligne - Assistant(e) RH',
    'Une nature de prestation ne s''affiche pas à l''enregistrement d''opération de caisse',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1947',
    'Assistance - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Paramétrage RH en ligne pour les salaires',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    32.50,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Assistance'
  ),
  (
    'OBCS-1946',
    'Assistance - Explication en ligne - Contrôleur de gestion',
    'Assistance sur demande d''absence et congés',
    'N''GBRA MOYE BERNICE DORIS',
    'MATRELEC',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.60,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1945',
    'Relance sur Requête en cours - Redirection vers ressources OBC - Chef de Projet',
    'Facture en doublon dans les lignes budgetaires prévu-réalisé',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.28,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    '2024-06-19T09:57:00.000Z'::timestamptz,
    'Redirection vers ressources OBC',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-1944',
    'Relance sur Requête en cours - Autres (Précisez dans la description) - Directeur Administratif et Financier',
    'Séance de paramétrage - Paramétrage en ligne pour les salaires du mois de janvier 2023',
    'N''GBRA MOYE BERNICE DORIS',
    'S-TEL',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    19.50,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-1943',
    'Assistance - Explication en ligne - Comptable',
    'Modification de compte G, explication processus d''imputation et d''enregistrement de facture auto / Manuel',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    85.00,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1942',
    'Assistance - Explication en ligne - Assistant(e) RH',
    'Taux d''accident de travail à changer et vérifier le salaire d''un employé qui a varié',
    'JOEL SIE',
    'ELIO GROUP',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    13.00,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1941',
    'Assistance - Explication en ligne - Comptable',
    'Assistance achat import',
    'JOEL SIE',
    'KORI TRANSPORT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1940',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Assistance - Création N° poste comptable tiers (Employé)',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.51,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1939',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Eléments variable',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.80,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1938',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Eléments variable',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    5.57,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1937',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Eléments variable',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    0.18,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1936',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Définition élément variable',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    7.32,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1935',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Suite - Assistance paramétrage éléments variable',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    15.00,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1934',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Assistance en ligne - Définition d''éléments variable',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    3.00,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    '2024-06-19T09:56:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1932',
    'Autres - Séance Google Meet/Zoom - Responsable Achat',
    'Présentation ENVAL LABORATOIRE pour les nouveaux responsables achat-logistique et parc-automobile',
    'N''GBRA MOYE BERNICE DORIS',
    'ENVAL LABORATOIRE',
    NULL,
    NULL,
    NULL,
    NULL,
    'Online (Google Meet, Teams...)',
    NULL,
    'Terminé',
    115.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Séance Google Meet/Zoom',
    'Autres'
  ),
  (
    'OBCS-1931',
    'Autres - Explication en ligne - Gestionnaire de stock',
    'Explication sur une sortie de plusieurs articles dont un article n''a pas de quantité suffisante',
    'JOEL SIE',
    'SIS',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique - BIS',
    NULL,
    'Terminé',
    12.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Autres'
  ),
  (
    'OBCS-1930',
    'Assistance - Explication en ligne - Comptable',
    'Traitement & Enregistrement du RAN',
    'Edwidge Kouassi',
    'SIAM',
    NULL,
    NULL,
    NULL,
    NULL,
    'Chat WhatsApp',
    NULL,
    'Terminé',
    6.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1929',
    'Autres - Autres (Précisez dans la description) - Chef de Projet',
    'Call - En séance de travail - Rappelez dans 1 Heure',
    'Edwidge Kouassi',
    'IVOIRE DEVELOPPEMENT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Autres (Précisez dans la description)',
    'Autres'
  ),
  (
    'OBCS-1928',
    'Assistance - Explication en ligne - Comptable',
    'Rattacher les fournisseur lié au 401000 au CG 401100 (Voir avec l''assistance Comptable)',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.42,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1927',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Rechercher les comptes clients rattaché au 411 puis modifier le compte général par 4111 (Suite)',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    1.21,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-1926',
    'Assistance - Explication en ligne - Comptable',
    'Rechercher les comptes clients rattaché au 411 puis modifier le compte général par 4111 - Suite',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1925',
    'Relance sur Requête en cours - Explication en ligne - Comptable',
    'Rechercher les comptes clients rattaché au 411 puis modifier le compte général par 4111',
    'Edwidge Kouassi',
    'JOEL K PROPERTIES',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Relance sur Requête en cours'
  ),
  (
    'OBCS-1924',
    'Assistance - Explication en ligne - Comptable',
    'La signification de M et A dans les journaux et la raison pour laquelle une écriture peut ne pas s''afficher dans le journal',
    'JOEL SIE',
    'KORI TRANSPORT',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    4.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  ),
  (
    'OBCS-1923',
    'Assistance - Explication en ligne - Directeur des Ressources Humaines',
    'Accès fonctionnalités module RH',
    'Edwidge Kouassi',
    'CILAGRI',
    NULL,
    NULL,
    NULL,
    NULL,
    'Appel Téléphonique',
    NULL,
    'Terminé',
    2.00,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    '2024-06-18T19:14:00.000Z'::timestamptz,
    'Explication en ligne',
    'Assistance'
  );

-- ============================================
-- ÉTAPE 3: UPSERT dans la table tickets (utilise ON CONFLICT sur jira_issue_key)
-- ============================================

DO $$
DECLARE
  v_ticket RECORD;
  v_obc_product_id UUID := '91304e02-2ce6-4811-b19d-1cae091a6fde';
  v_global_module_id UUID := '98ce1c5f-e53c-4baf-9af1-52255d499378';
  v_company_id UUID;
  v_reporter_id UUID;
  v_contact_user_id UUID;
  v_module_id UUID;
  v_submodule_id UUID;
  v_ticket_id UUID;
  v_status TEXT;
  v_priority priority_t;
  v_canal canal_t;
BEGIN
  FOR v_ticket IN SELECT * FROM temp_assistance_tickets LOOP
    -- 1. Créer ou récupérer l'entreprise
    SELECT id INTO v_company_id
    FROM companies
    WHERE name = TRIM(v_ticket.client_name)
    LIMIT 1;
    
    IF v_company_id IS NULL THEN
      INSERT INTO companies (name)
      VALUES (TRIM(v_ticket.client_name))
      RETURNING id INTO v_company_id;
    END IF;
    
    -- 2. Créer ou récupérer le rapporteur (reporter)
    IF v_ticket.reporter_name IS NOT NULL AND TRIM(v_ticket.reporter_name) != '' THEN
      v_reporter_id := (
        SELECT id FROM profiles
        WHERE email = LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM(v_ticket.reporter_name), '[^a-zA-Z0-9\s]', '', 'g'), '\s+', '.', 'g')) || '@assistance.onpoint.local'
        LIMIT 1
      );
      
      IF v_reporter_id IS NULL THEN
        INSERT INTO profiles (full_name, email, role, company_id, job_title, is_active)
        VALUES (
          TRIM(v_ticket.reporter_name),
          LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM(v_ticket.reporter_name), '[^a-zA-Z0-9\s]', '', 'g'), '\s+', '.', 'g')) || '@assistance.onpoint.local',
          'agent',
          NULL,
          NULLIF(TRIM(v_ticket.job_title), ''),
          true
        )
        ON CONFLICT (email) DO UPDATE SET
          full_name = EXCLUDED.full_name,
          job_title = COALESCE(EXCLUDED.job_title, profiles.job_title)
        RETURNING id INTO v_reporter_id;
      END IF;
    END IF;
    
    -- 3. Créer ou récupérer l'utilisateur contact
    IF v_ticket.contact_user_name IS NOT NULL AND TRIM(v_ticket.contact_user_name) != '' THEN
      v_contact_user_id := (
        SELECT id FROM profiles
        WHERE email = LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM(v_ticket.contact_user_name), '[^a-zA-Z0-9\s]', '', 'g'), '\s+', '.', 'g')) || '@assistance.onpoint.local'
        LIMIT 1
      );
      
      IF v_contact_user_id IS NULL THEN
        INSERT INTO profiles (full_name, email, role, company_id, job_title, is_active)
        VALUES (
          TRIM(v_ticket.contact_user_name),
          LOWER(REGEXP_REPLACE(REGEXP_REPLACE(TRIM(v_ticket.contact_user_name), '[^a-zA-Z0-9\s]', '', 'g'), '\s+', '.', 'g')) || '@assistance.onpoint.local',
          'client',
          v_company_id,
          NULLIF(TRIM(v_ticket.job_title), ''),
          true
        )
        ON CONFLICT (email) DO UPDATE SET
          full_name = EXCLUDED.full_name,
          company_id = COALESCE(EXCLUDED.company_id, profiles.company_id),
          job_title = COALESCE(EXCLUDED.job_title, profiles.job_title)
        RETURNING id INTO v_contact_user_id;
      END IF;
    END IF;
    
    -- 4. Créer ou récupérer le module
    IF v_ticket.module_name IS NOT NULL AND TRIM(v_ticket.module_name) != '' THEN
      v_module_id := (
        SELECT id FROM modules
        WHERE name = TRIM(v_ticket.module_name) AND product_id = v_obc_product_id
        LIMIT 1
      );
      
      IF v_module_id IS NULL THEN
        INSERT INTO modules (name, product_id)
        VALUES (TRIM(v_ticket.module_name), v_obc_product_id)
        RETURNING id INTO v_module_id;
      END IF;
    ELSE
      v_module_id := v_global_module_id;
    END IF;
    
    -- 5. Créer ou récupérer le sous-module
    IF v_ticket.submodule_name IS NOT NULL AND TRIM(v_ticket.submodule_name) != '' THEN
      v_submodule_id := (
        SELECT id FROM submodules
        WHERE name = TRIM(v_ticket.submodule_name) AND module_id = v_module_id
        LIMIT 1
      );
      
      IF v_submodule_id IS NULL THEN
        INSERT INTO submodules (name, module_id)
        VALUES (TRIM(v_ticket.submodule_name), v_module_id)
        RETURNING id INTO v_submodule_id;
      END IF;
    END IF;
    
    -- 6. UPSERT du ticket (ON CONFLICT sur jira_issue_key)
    -- Mapper les valeurs avant l'INSERT
    -- Mapper le statut
      IF UPPER(TRIM(v_ticket.status)) LIKE '%TERMINÉ%' OR UPPER(TRIM(v_ticket.status)) LIKE '%TERMINE%' OR UPPER(TRIM(v_ticket.status)) LIKE '%RÉSOLU%' OR UPPER(TRIM(v_ticket.status)) LIKE '%RESOLU%' THEN
        v_status := 'Resolue';
      ELSIF UPPER(TRIM(v_ticket.status)) LIKE '%EN COURS%' OR UPPER(TRIM(v_ticket.status)) LIKE '%EN TRAITEMENT%' THEN
        v_status := 'En cours';
      ELSIF UPPER(TRIM(v_ticket.status)) LIKE '%EN ATTENTE%' THEN
        v_status := 'En attente';
      ELSE
        v_status := 'Nouveau';
      END IF;
      
      -- Mapper la priorité
      IF UPPER(TRIM(v_ticket.priority)) LIKE '%PRIORITÉ 1%' OR UPPER(TRIM(v_ticket.priority)) LIKE '%PRIORITE 1%' OR UPPER(TRIM(v_ticket.priority)) LIKE '%CRITIQUE%' THEN
        v_priority := 'Critical'::priority_t;
      ELSIF UPPER(TRIM(v_ticket.priority)) LIKE '%PRIORITÉ 2%' OR UPPER(TRIM(v_ticket.priority)) LIKE '%PRIORITE 2%' OR UPPER(TRIM(v_ticket.priority)) LIKE '%HAUTE%' THEN
        v_priority := 'High'::priority_t;
      ELSE
        v_priority := 'Low'::priority_t;
      END IF;
      
      -- Mapper le canal
      IF UPPER(TRIM(v_ticket.canal)) LIKE '%APPEL TÉLÉPHONIQUE%' OR UPPER(TRIM(v_ticket.canal)) LIKE '%APPEL TELEPHONIQUE%' THEN
        v_canal := 'Appel Téléphonique'::canal_t;
      ELSIF UPPER(TRIM(v_ticket.canal)) LIKE '%APPEL WHATSAPP%' THEN
        v_canal := 'Appel WhatsApp'::canal_t;
      ELSIF UPPER(TRIM(v_ticket.canal)) LIKE '%CHAT WHATSAPP%' THEN
        v_canal := 'Chat WhatsApp'::canal_t;
      ELSIF UPPER(TRIM(v_ticket.canal)) LIKE '%CHAT SMS%' THEN
        v_canal := 'Chat SMS'::canal_t;
      ELSIF UPPER(TRIM(v_ticket.canal)) LIKE '%E-MAIL%' OR UPPER(TRIM(v_ticket.canal)) LIKE '%EMAIL%' THEN
        v_canal := 'E-mail'::canal_t;
      ELSIF UPPER(TRIM(v_ticket.canal)) LIKE '%PRÉSENTIEL%' OR UPPER(TRIM(v_ticket.canal)) LIKE '%PRESENTIEL%' THEN
        v_canal := 'En présentiel'::canal_t;
      ELSIF UPPER(TRIM(v_ticket.canal)) LIKE '%ONLINE%' OR UPPER(TRIM(v_ticket.canal)) LIKE '%GOOGLE MEET%' OR UPPER(TRIM(v_ticket.canal)) LIKE '%TEAMS%' THEN
        v_canal := 'Online (Google Meet, Teams...)'::canal_t;
      ELSE
        v_canal := 'Autre'::canal_t;
      END IF;
      
      INSERT INTO tickets (
        jira_issue_key,
        title,
        description,
        ticket_type,
        status,
        priority,
        canal,
        company_id,
        created_by,
        contact_user_id,
        module_id,
        submodule_id,
        duration_minutes,
        created_at,
        updated_at,
        action_menee,
        objet_principal,
        affects_all_companies
      )
      VALUES (
        v_ticket.jira_issue_key,
        TRIM(v_ticket.title),
        NULLIF(TRIM(v_ticket.description), ''),
        'ASSISTANCE',
        v_status,
        v_priority,
        v_canal,
        v_company_id,
        v_reporter_id,
        v_contact_user_id,
        v_module_id,
        v_submodule_id,
        NULLIF(v_ticket.duration_minutes::DECIMAL, 0),
        COALESCE(v_ticket.created_at, NOW()),
        COALESCE(v_ticket.updated_at, v_ticket.created_at, NOW()),
        NULLIF(TRIM(v_ticket.action_menee), ''),
        NULLIF(TRIM(v_ticket.objet_principal), ''),
        false
      )
      ON CONFLICT (jira_issue_key) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        status = EXCLUDED.status,
        priority = EXCLUDED.priority,
        canal = EXCLUDED.canal,
        company_id = EXCLUDED.company_id,
        created_by = COALESCE(EXCLUDED.created_by, tickets.created_by),
        contact_user_id = COALESCE(EXCLUDED.contact_user_id, tickets.contact_user_id),
        module_id = EXCLUDED.module_id,
        submodule_id = EXCLUDED.submodule_id,
        duration_minutes = EXCLUDED.duration_minutes,
        created_at = COALESCE(EXCLUDED.created_at, tickets.created_at),
        updated_at = EXCLUDED.updated_at,
        action_menee = COALESCE(EXCLUDED.action_menee, tickets.action_menee),
        objet_principal = COALESCE(EXCLUDED.objet_principal, tickets.objet_principal);
  END LOOP;
END $$;

-- Nettoyer la table temporaire
DROP TABLE IF EXISTS temp_assistance_tickets;
